[address]
other = "address"
[channel]
other = "channel"
[client_desktop]
other = "Desktop"
[client_mobile]
other = "Mobile"
[client_web]
other = "Web"
[command_panel]
other = "panel"
[command_panel_desc]
other = "manage or create panel"
[command_panel_option_config]
other = "config"
[command_panel_option_config_desc]
other = "configure proprties"
[command_panel_option_config_option_emoji]
other = "emoji"
[command_panel_option_config_option_emoji_desc]
other = "Set custom emoji in select menu"
[command_panel_option_config_option_emoji_message]
other = "Please send emoji in this channel"
[command_panel_option_desc_role]
other = "manage role panel"
[command_panel_option_minecraft]
other = "minecraft"
[command_panel_option_minecraft_desc]
other = "manage minecraft panel"
[command_panel_option_minecraft_message]
other = "To add a server right click or long press on the message and press \"Apps\" then \"modify\""
[command_panel_option_minecraft_option_create]
other = "create"
[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"
[command_panel_option_minecraft_option_create_option_address]
other = "address"
[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"
[command_panel_option_minecraft_option_create_option_description]
other = "description"
[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"
[command_panel_option_minecraft_option_create_option_name]
other = "name"
[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"
[command_panel_option_minecraft_option_create_option_port]
other = "port"
[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"
[command_panel_option_minecraft_option_create_option_servername]
other = "servername"
[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"
[command_panel_option_minecraft_option_create_option_showip]
other = "showip"
[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"
[command_panel_option_minecraft_placeholder]
other = "Select server"
[command_panel_option_role]
other = "role"
[command_panel_option_role_message]
other = "To add a role right click or press and hold on the message and press \"Apps\" then \"modify\""
[command_panel_option_role_option_create]
other = "create"
[command_panel_option_role_option_create_option_desc]
other = "desc"
[command_panel_option_role_option_create_option_desc_desc]
other = "desc of panel"
[command_panel_option_role_option_create_option_desc_name]
other = "name of panel"
[command_panel_option_role_option_create_option_desc_role]
other = "role that add to the panel"
[command_panel_option_role_option_create_option_name]
other = "name"
[command_panel_option_role_option_create_option_role]
other = "role"
[command_panel_option_role_option_desc_create]
other = "create role panel"
[command_role]
other = "role"
[command_role_desc]
other = "manage role"
[command_role_option_color]
other = "color"
[command_role_option_color_desc]
other = "create color role"
[command_role_option_color_option_name]
other = "name"
[command_role_option_color_option_name_desc]
other = "name of role"
[command_role_option_color_option_rgb]
other = "rgb"
[command_role_option_color_option_rgb_desc]
other = "rgb color code"
[command_tracker]
other = "tracker"
[command_tracker_desc]
other = "manage or create tracker"
[command_tracker_option_minecraft]
other = "minecraft"
[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"
[command_tracker_option_minecraft_option_create]
other = "create"
[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"
[command_tracker_option_minecraft_option_create_option_address]
other = "address"
[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"
[command_tracker_option_minecraft_option_create_option_name]
other = "name"
[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"
[command_tracker_option_minecraft_option_create_option_port]
other = "port"
[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"
[command_tracker_option_minecraft_option_create_option_role]
other = "role"
[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"
[command_tracker_option_minecraft_option_get]
other = "get"
[command_tracker_option_minecraft_option_get_desc]
other = "get minecraft trackers"
[command_tracker_option_minecraft_option_remove]
other = "remove"
[command_tracker_option_minecraft_option_remove_desc]
other = "remove minecraft trackers"
[command_tracker_option_minecraft_option_remove_option_name]
other = "name"
[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "name of tracker"
[error]
other = "{{.Error}}"
[error_0]
other = "An error has occurred {{.Error}}"
[error_TargetIsBot]
other = "Cannot select this bot as target!"
[error_bot_does_not_have_permissions]
other = "Insufficient bot permissions!\rIt must be given administrator permission by the server admin to work!"
[error_cannot_read_content]
other = "Cant read message content."
[error_cannot_use_roles]
other = "The following roles cannot be used"
[error_failed_to_connect_api]
other = "failed to connect api server error"
[error_failed_to_ping_server]
other = "failed to ping server"
[error_invalid_port_value]
other = "invalid port value"
[error_invalid_roles]
other = "Invalid role(s)"
[error_message]
other = "An error has occurred"
[error_unknown_command]
other = "Unkown operation"
[feed_minecraft_webhook_name]
other = "server notifier"
[latency]
other = "latency"
[message_command_modify]
other = "modify"
[message_command_select]
other = "select"
[message_command_select_message]
other = "selected"
[message_command_user_info]
other = "info"
[message_command_user_info_color_code]
other = "Color Code"
[message_command_user_info_id]
other = "ID"
[message_command_user_info_joined_at]
other = "Joined at"
[message_command_user_info_nick]
other = "Nick"
[message_command_user_info_none]
other = "none"
[message_command_user_info_roles]
other = "Roles"
[message_command_user_info_status]
other = "Status"
[message_command_pin]
other = "pin message"
[message_modify_cant_use_this_message_error]
other = "not available for that message"
[message_modify_role_add_message]
other = "Choose a role to add"
[message_modify_role_create_message]
other = "Coose a role to create panel"
[online_status]
other = "Status"
[panel_minecraft_add_server]
other = "Add a server"
[panel_minecraft_address]
other = "Address"
[panel_minecraft_display_name]
other = "Display Name"
[panel_minecraft_message_boot]
other = "booted {{.Name}}"
[panel_minecraft_message_stop]
other = "stopped {{.Name}}"
[panel_minecraft_my_server]
other = "My server"
[panel_minecraft_port]
other = "Port"
[panel_role_message_added]
other = "added"
[panel_role_message_removed]
other = "removed"
[players]
other = "players"
[port]
other = "port"
[version]
other = "version"
