[address]
other = "Adresa"

[channel]
other = "kanál"

[client_desktop]
other = "Stolní počítače"

[client_mobile]
other = "Mobil"

[client_web]
other = "Webová"

[command_message]
other = "zpráva"

[command_message_description]
other = "spravovat a odesílat zprávu"

[command_message_embed]
other = "vložený"

[command_message_embed_color]
other = "barva"

[command_message_embed_color_description]
other = "rgb kód vložené barvy"

[command_message_embed_content]
other = "Obsah"

[command_message_embed_content_description]
other = "obsah zprávy"

[command_message_embed_description]
other = "poslat zprávu s webhookem"

[command_message_embed_embed_content]
other = "vložený obsah"

[command_message_embed_embed_content_description]
other = "obsah vložené zprávy"

[command_message_embed_embed_title]
other = "titulek"

[command_message_embed_embed_title_description]
other = "název vložené zprávy"

[command_message_embed_icon_url]
other = "URL ikony"

[command_message_embed_icon_url_description]
other = "URL avateru uživatele"

[command_message_embed_username]
other = "uživatelské jméno"

[command_message_embed_username_description]
other = "jméno odesílatele zprávy"

[command_message_webhook]
other = "webový háček"

[command_message_webhook_description]
other = "odeslat zprávu webhooku"

[command_panel]
other = "panel"

[command_panel_desc]
other = "spravovat nebo vytvářet panel"

[command_panel_option_config]
other = "konfigurace"

[command_panel_option_config_desc]
other = "konfigurovat propruty"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Nastavit vlastní emoji ve vybrané nabídce"

[command_panel_option_config_option_emoji_message]
other = "Zašlete prosím emoji do tohoto kanálu"

[command_panel_option_desc_role]
other = "spravovat panel rolí"

[command_panel_option_minecraft]
other = "těžební plošina"

[command_panel_option_minecraft_desc]
other = "Spravovat panel minecraft"

[command_panel_option_minecraft_message]
other = 'Pro přidání serveru klikněte pravým nebo dlouhým stiskem na zprávě a stiskněte tlačítko "Aplikace" a poté "upravit"'

[command_panel_option_minecraft_option_create]
other = "vytvořit"

[command_panel_option_minecraft_option_create_desc]
other = "vytvořit panel minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Adresa"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_panel_option_minecraft_option_create_option_description]
other = "Popis"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "popis poradní skupiny"

[command_panel_option_minecraft_option_create_option_name]
other = "jméno"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "název dílce"

[command_panel_option_minecraft_option_create_option_port]
other = "přístav"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_panel_option_minecraft_option_create_option_servername]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "zobrazit IP nebo ne"

[command_panel_option_minecraft_placeholder]
other = "Vybrat server"

[command_panel_option_role]
other = "role"

[command_panel_option_role_message]
other = 'Pro přidání role klikněte pravým tlačítkem myši nebo podržte zprávu a stiskněte tlačítko "Aplikace" a poté "upravit"'

[command_panel_option_role_option_create]
other = "vytvořit"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "sesta dílce"

[command_panel_option_role_option_create_option_desc_name]
other = "název dílce"

[command_panel_option_role_option_create_option_desc_role]
other = "role, která přidává do panelu"

[command_panel_option_role_option_create_option_name]
other = "jméno"

[command_panel_option_role_option_create_option_role]
other = "role"

[command_panel_option_role_option_desc_create]
other = "vytvořit panel role"

[command_panel_vote]
other = "Hlasovat"

[command_panel_vote_create]
other = "vytvořit"

[command_panel_vote_create_desc]
other = "vytvořit hlasový panel"

[command_panel_vote_create_description]
other = "Popis"

[command_panel_vote_create_description_desc]
other = "popis volební komise"

[command_panel_vote_create_max_choice]
other = "maximální volba"

[command_panel_vote_create_max_choice_desc]
other = "maximální počet možností"

[command_panel_vote_create_message_add]
other = "Přidat"

[command_panel_vote_create_message_add_choice]
other = "Přidat volbu"

[command_panel_vote_create_message_add_vote_choice]
other = "Přidat volbu hlasování"

[command_panel_vote_create_message_create]
other = "Vytvořit"

[command_panel_vote_create_message_end_at]
other = "Konec v"

[command_panel_vote_create_message_start_at]
other = "Start at"

[command_panel_vote_create_message_max]
other = "Max."

[command_panel_vote_create_message_min]
other = "Min."

[command_panel_vote_create_message_modal_description]
other = "L 343, 22.12.2009, s. 1)."

[command_panel_vote_create_message_modal_description_desc]
other = "Popis volby hlasování"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "volitelné"

[command_panel_vote_create_message_modal_title]
other = "Hlava 1 – Celkem"

[command_panel_vote_create_message_modal_title_desc]
other = "Název volby hlasování"

[command_panel_vote_create_message_no_desc]
other = "žádný popis"

[command_panel_vote_create_message_vote_info]
other = "Informace o hlasování"

[command_panel_vote_create_min_choice]
other = "min. volba"

[command_panel_vote_create_min_choice_desc]
other = "minimální počet možností"

[command_panel_vote_create_show_count]
other = "zobrazit počet"

[command_panel_vote_create_show_count_desc]
other = "zobrazit hodnoty hlasování"

[command_panel_vote_create_time]
other = "Lhůta"

[command_panel_vote_create_time_desc]
other = "Lhůta hlasovacího panelu"

[command_panel_vote_create_time_unit]
other = "časová jednotka"

[command_panel_vote_create_time_unit_day]
one = "den"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "Jednotka časového limitu"

[command_panel_vote_create_time_unit_hour]
one = "hodina"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "minuta"
other = "minute"

[command_panel_vote_create_title]
other = "titulek"

[command_panel_vote_create_title_desc]
other = "Název hlasovacího panelu"

[command_panel_vote_desc]
other = "spravovat a vytvářet hlasovací panel"

[command_panel_vote_message_finished]
other = "Hlasování dokončeno!"

[command_panel_vote_message_result]
other = "Výsledek"

[command_panel_vote_message_voted]
other = "Hlasováno!"

[command_panel_vote_message_winner]
other = "Vítěz"

[command_panel_vote_votes]
one = "{{.Vote}} hlas"
other = "{{.Vote}} hlasů"

[command_role]
other = "role"

[command_role_desc]
other = "spravovat roli"

[command_role_option_color]
other = "barva"

[command_role_option_color_desc]
other = "vytvořit barevnou roli"

[command_role_option_color_option_name]
other = "jméno"

[command_role_option_color_option_name_desc]
other = "název role"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb barevný kód"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "spravovat nebo vytvářet tracker"

[command_tracker_option_minecraft]
other = "těžební plošina"

[command_tracker_option_minecraft_desc]
other = "spravovat tracker serveru minecraft"

[command_tracker_option_minecraft_option_create]
other = "vytvořit"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveru minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "Adresa"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_tracker_option_minecraft_option_create_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "jméno serveru"

[command_tracker_option_minecraft_option_create_option_port]
other = "přístav"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role ke zmínění"

[command_tracker_option_minecraft_option_get]
other = "získej"

[command_tracker_option_minecraft_option_get_desc]
other = "získat trackery minecraft"

[command_tracker_option_minecraft_option_remove]
other = "odstranit"

[command_tracker_option_minecraft_option_remove_desc]
other = "odstranit minecraft trackery"

[command_tracker_option_minecraft_option_remove_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "název trackeru"

[error]
other = "{{.Error}}"

[error_0]
other = "Došlo k chybě {{.Error}}"

[error_TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error_bot_does_not_have_permissions]
other = "Nedostatečná oprávnění bota!\rMusí být správcem serveru uděleno oprávnění správce!"

[error_cannot_read_content]
other = "Přeskočit obsah zpráv."

[error_cannot_use_roles]
other = "Následující role nelze použít"

[error_failed_to_connect_api]
other = "chyba api serveru se nezdařila"

[error_failed_to_ping_server]
other = "pingový server selhal"

[error_invalid_port_value]
other = "neplatná hodnota portu"

[error_invalid_roles]
other = "Neplatná role"

[error_message]
other = "Došlo k chybě"

[error_unknown_command]
other = "Neznámý provoz"

[feed_minecraft_webhook_name]
other = "oznámení serveru"

[latency]
other = "odezva"

[message_command_modify]
other = "upravit"

[message_command_pin]
other = "pin zpráva"

[message_command_select]
other = "vybrat"

[message_command_select_message]
other = "vybráno"

[message_command_user_info]
other = "informace"

[message_command_user_info_color_code]
other = "Kód barvy"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Přidal/a se k"

[message_command_user_info_nick]
other = "Přezdívka"

[message_command_user_info_none]
other = "žádný"

[message_command_user_info_roles]
other = "Role"

[message_command_user_info_status]
other = "Stav"

[message_modify_cant_use_this_message_error]
other = "není k dispozici pro tuto zprávu"

[message_modify_role_add_message]
other = "Vyberte roli pro přidání"

[message_modify_role_create_message]
other = "Přetáhni roli pro vytvoření panelu"

[online_status]
other = "Stav"

[panel_minecraft_add_server]
other = "Přidat server"

[panel_minecraft_address]
other = "Adresa"

[panel_minecraft_display_name]
other = "Zobrazované jméno"

[panel_minecraft_message_boot]
other = "spuštěno {{.Name}}"

[panel_minecraft_message_stop]
other = "zastavil {{.Name}}"

[panel_minecraft_my_server]
other = "Můj server"

[panel_minecraft_port]
other = "Přístav"

[panel_role_message_added]
other = "přidáno"

[panel_role_message_removed]
other = "odstraněno"

[players]
other = "hráči"

[port]
other = "přístav"

[version]
other = "verze"
