[address]
other = "adresse"

[channel]
other = "kanal"

[client_desktop]
other = "Desktop"

[client_mobile]
other = "Mobil"

[client_web]
other = "Web"

[command_message]
other = "nachricht"

[command_message_description]
other = "verwalten und Nachricht senden"

[command_message_embed]
other = "einbetten"

[command_message_embed_color]
other = "farben"

[command_message_embed_color_description]
other = "rgb Code der Einbettfarbe"

[command_message_embed_content]
other = "inhalt"

[command_message_embed_content_description]
other = "Inhalt der Nachricht"

[command_message_embed_description]
other = "sende eingebettete Nachricht mit Webhook"

[command_message_embed_embed_content]
other = "einbetten Inhalt"

[command_message_embed_embed_content_description]
other = "Inhalt der Nachricht einbetten"

[command_message_embed_embed_title]
other = "titel"

[command_message_embed_embed_title_description]
other = "titel der Nachrichteneinbettung"

[command_message_embed_icon_url]
other = "symbol-URL"

[command_message_embed_icon_url_description]
other = "url des Benutzer-avater"

[command_message_embed_username]
other = "benutzername"

[command_message_embed_username_description]
other = "name des Nachrichtensenders"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "sende Webhook Nachricht"

[command_panel]
other = "panel"

[command_panel_desc]
other = "verwalten oder Panel erstellen"

[command_panel_option_config]
other = "Konfiguration"

[command_panel_option_config_desc]
other = "konfiguriere Proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Eigene Emoji im Auswahlmenü festlegen"

[command_panel_option_config_option_emoji_message]
other = "Bitte sende Emoji in diesem Kanal"

[command_panel_option_desc_role]
other = "verwalte Rollen"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "minecraft-Panel verwalten"

[command_panel_option_minecraft_message]
other = 'Um einen Server hinzuzufügen, klicken Sie mit der rechten Maustaste oder drücken Sie lange auf die Nachricht und drücken Sie "Apps" und dann "ändern"'

[command_panel_option_minecraft_option_create]
other = "erstellen"

[command_panel_option_minecraft_option_create_desc]
other = "erstelle Minecraft-Panel"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "Adresse des Servers"

[command_panel_option_minecraft_option_create_option_description]
other = "beschreibung"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "Beschreibung des Panels"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "Name des Panels"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port des Servers"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "Name des Servers"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "zeige ip oder nicht"

[command_panel_option_minecraft_placeholder]
other = "Server auswählen"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_message]
other = 'Um eine Rolle hinzuzufügen, klicken Sie mit der rechten Maustaste oder drücken Sie die Nachricht und drücken Sie "Apps" und dann "ändern"'

[command_panel_option_role_option_create]
other = "erstellen"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc des Panels"

[command_panel_option_role_option_create_option_desc_name]
other = "Name des Panels"

[command_panel_option_role_option_create_option_desc_role]
other = "Rolle, die dem Panel hinzugefügt wird"

[command_panel_option_role_option_create_option_name]
other = "name"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "erstelle Rollen-Panel"

[command_panel_vote]
other = "abstimmen"

[command_panel_vote_create]
other = "erstellen"

[command_panel_vote_create_desc]
other = "erstelle Abstimmungs-Panel"

[command_panel_vote_create_description]
other = "beschreibung"

[command_panel_vote_create_description_desc]
other = "beschreibung des Stimmen-Panels"

[command_panel_vote_create_max_choice]
other = "maximale Auswahl"

[command_panel_vote_create_max_choice_desc]
other = "maximale Anzahl an Optionen"

[command_panel_vote_create_message_add]
other = "Neu"

[command_panel_vote_create_message_add_choice]
other = "Auswahl hinzufügen"

[command_panel_vote_create_message_add_vote_choice]
other = "Auswahl hinzufügen"

[command_panel_vote_create_message_create]
other = "Anlegen"

[command_panel_vote_create_message_end_at]
other = "Endet am"

[command_panel_vote_create_message_max]
other = "Max."

[command_panel_vote_create_message_min]
other = "Min"

[command_panel_vote_create_message_modal_description]
other = "Beschreibung"

[command_panel_vote_create_message_modal_description_desc]
other = "Beschreibung der Wahl der Stimme"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "optional"

[command_panel_vote_create_message_modal_title]
other = "Titel"

[command_panel_vote_create_message_modal_title_desc]
other = "Titel der Wahl der Stimme"

[command_panel_vote_create_message_no_desc]
other = "keine Beschreibung"

[command_panel_vote_create_message_vote_info]
other = "Bewertungsinformationen"

[command_panel_vote_create_min_choice]
other = "Min. Auswahl"

[command_panel_vote_create_min_choice_desc]
other = "minimun Anzahl von Optionen"

[command_panel_vote_create_show_count]
other = "zeige Anzahl"

[command_panel_vote_create_show_count_desc]
other = "die Werte der Abstimmung anzeigen"

[command_panel_vote_create_time]
other = "zeitlimit"

[command_panel_vote_create_time_desc]
other = "zeitliche Begrenzung des Abstimmungs-Panels"

[command_panel_vote_create_time_unit]
other = "Zeiteinheit"

[command_panel_vote_create_time_unit_day]
one = "tag"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "Zeitlimit"

[command_panel_vote_create_time_unit_hour]
one = "std"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "minute"
other = "minute"

[command_panel_vote_create_title]
other = "titel"

[command_panel_vote_create_title_desc]
other = "der Titel des Abstimmungs-Panels"

[command_panel_vote_desc]
other = "verwalten und Abstimmung-Panel erstellen"

[command_panel_vote_message_finished]
other = "Abstimmung beendet!"

[command_panel_vote_message_result]
other = "Ergebnis"

[command_panel_vote_message_voted]
other = "Voted!"

[command_panel_vote_message_winner]
other = "Sieger"

[command_panel_vote_votes]
one = "{{.Vote}} Stimmen"
other = "{{.Vote}} Stimmen"

[command_role]
other = "rolle"

[command_role_desc]
other = "Rolle verwalten"

[command_role_option_color]
other = "farben"

[command_role_option_color_desc]
other = "erstelle Farbrolle"

[command_role_option_color_option_name]
other = "name"

[command_role_option_color_option_name_desc]
other = "name der Rolle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb Farbcode"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "verwalten oder Tracker erstellen"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "minecraft Server Tracker verwalten"

[command_tracker_option_minecraft_option_create]
other = "erstellen"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft Server Tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "Adresse des Servers"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "Name des Servers"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port des Servers"

[command_tracker_option_minecraft_option_create_option_role]
other = "rolle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "zu nennende Rolle"

[command_tracker_option_minecraft_option_get]
other = "holen"

[command_tracker_option_minecraft_option_get_desc]
other = "erhalte Minecraft-Tracker"

[command_tracker_option_minecraft_option_remove]
other = "entfernen"

[command_tracker_option_minecraft_option_remove_desc]
other = "minecraft-Tracker entfernen"

[command_tracker_option_minecraft_option_remove_option_name]
other = "name"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "Name des Trackers"

[error]
other = "{{.Error}}"

[error_0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error_TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error_bot_does_not_have_permissions]
other = "Unzureichende Bot-Berechtigungen!\rDer Server-Administrator muss ihm Administratorrechte erteilen, um zu funktionieren!"

[error_cannot_read_content]
other = "Cant Lese-Nachrichten-Inhalt."

[error_cannot_use_roles]
other = "Die folgenden Rollen können nicht verwendet werden"

[error_failed_to_connect_api]
other = "konnte Api-Server nicht verbinden"

[error_failed_to_ping_server]
other = "konnte Server nicht pingen"

[error_invalid_port_value]
other = "ungültiger Port-Wert"

[error_invalid_roles]
other = "Ungültige Rolle(n)"

[error_message]
other = "Ein Fehler ist aufgetreten"

[error_unknown_command]
other = "Unbekannte Operation"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latenz"

[message_command_modify]
other = "ändern"

[message_command_pin]
other = "pin-Nachricht"

[message_command_select]
other = "wählen"

[message_command_select_message]
other = "ausgewählt"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Farbcode"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Beitreten bei"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "keine"

[message_command_user_info_roles]
other = "Rollen"

[message_command_user_info_status]
other = "Status"

[message_modify_cant_use_this_message_error]
other = "nicht verfügbar für diese Nachricht"

[message_modify_role_add_message]
other = "Rolle zum Hinzufügen auswählen"

[message_modify_role_create_message]
other = "Rolle kochen, um Panel zu erstellen"

[online_status]
other = "Status"

[panel_minecraft_add_server]
other = "Server hinzufügen"

[panel_minecraft_address]
other = "Adresse"

[panel_minecraft_display_name]
other = "Anzeigename"

[panel_minecraft_message_boot]
other = "{{.Name}} gebootet"

[panel_minecraft_message_stop]
other = "gestoppt {{.Name}}"

[panel_minecraft_my_server]
other = "Mein Server"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "hinzugefügt"

[panel_role_message_removed]
other = "entfernt"

[players]
other = "spieler"

[port]
other = "port"

[version]
other = "version"
