[address]
other = "διεύθυνση"

[channel]
other = "κανάλι"

[client_desktop]
other = "Επιφάνεια Εργασίας"

[client_mobile]
other = "Κινητό"

[client_web]
other = "Ιστός"

[command_message]
other = "μήνυμα"

[command_message_description]
other = "διαχείριση και αποστολή μηνύματος"

[command_message_embed]
other = "ενσωματωμένο"

[command_message_embed_color]
other = "χρώμα"

[command_message_embed_color_description]
other = "κωδικός rgb του ενσωματωμένου χρώματος"

[command_message_embed_content]
other = "περιεχόμενο"

[command_message_embed_content_description]
other = "περιεχόμενο του μηνύματος"

[command_message_embed_description]
other = "αποστολή ενσωματωμένου μηνύματος με webhook"

[command_message_embed_embed_content]
other = "ενσωματωμένο περιεχόμενο"

[command_message_embed_embed_content_description]
other = "περιεχόμενο ενσωματωμένου μηνύματος"

[command_message_embed_embed_title]
other = "τίτλος"

[command_message_embed_embed_title_description]
other = "τίτλος του ενσωματωμένου μηνύματος"

[command_message_embed_icon_url]
other = "εικονίδιο url"

[command_message_embed_icon_url_description]
other = "url του χρήστη avater"

[command_message_embed_username]
other = "όνομα χρήστη"

[command_message_embed_username_description]
other = "όνομα αποστολέα μηνύματος"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "αποστολή μηνύματος webhook"

[command_panel]
other = "πίνακας"

[command_panel_desc]
other = "διαχείριση ή δημιουργία πίνακα"

[command_panel_option_config]
other = "διαμόρφωση"

[command_panel_option_config_desc]
other = "ρύθμιση proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Ορισμός προσαρμοσμένων emoji στο μενού επιλογής"

[command_panel_option_config_option_emoji_message]
other = "Παρακαλώ στείλτε emoji σε αυτό το κανάλι"

[command_panel_option_desc_role]
other = "διαχείριση ρόλου πίνακα"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "διαχείριση πάνελ minecraft"

[command_panel_option_minecraft_message]
other = 'Για να προσθέσετε ένα διακομιστή κάντε δεξί κλικ ή πατήστε παρατεταμένα το μήνυμα και πατήστε "Εφαρμογές" και μετά "Τροποποίηση"'

[command_panel_option_minecraft_option_create]
other = "δημιουργία"

[command_panel_option_minecraft_option_create_desc]
other = "δημιούργησε πάνελ minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "διεύθυνση"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "διεύθυνση διακομιστή"

[command_panel_option_minecraft_option_create_option_description]
other = "περιγραφή"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "περιγραφή του πίνακα"

[command_panel_option_minecraft_option_create_option_name]
other = "όνομα"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "όνομα του πίνακα"

[command_panel_option_minecraft_option_create_option_port]
other = "θύρα"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "θύρα διακομιστή"

[command_panel_option_minecraft_option_create_option_servername]
other = "όνομα εξυπηρετητή"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "όνομα διακομιστή"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "εμφάνιση ip ή όχι"

[command_panel_option_minecraft_placeholder]
other = "Επιλογή διακομιστή"

[command_panel_option_role]
other = "ρόλος"

[command_panel_option_role_message]
other = 'Για να προσθέσετε ένα ρόλο κάντε δεξί κλικ ή πατήστε παρατεταμένα το μήνυμα και πατήστε "Εφαρμογές" και μετά "τροποποιήστε"'

[command_panel_option_role_option_create]
other = "δημιουργία"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "πίνακας του πίνακα"

[command_panel_option_role_option_create_option_desc_name]
other = "όνομα του πίνακα"

[command_panel_option_role_option_create_option_desc_role]
other = "ρόλος που προσθέτει στον πίνακα"

[command_panel_option_role_option_create_option_name]
other = "όνομα"

[command_panel_option_role_option_create_option_role]
other = "ρόλος"

[command_panel_option_role_option_desc_create]
other = "δημιουργία πίνακα ρόλου"

[command_panel_vote]
other = "ψήφος"

[command_panel_vote_create]
other = "δημιουργία"

[command_panel_vote_create_desc]
other = "δημιουργία πίνακα ψηφοφορίας"

[command_panel_vote_create_description]
other = "περιγραφή"

[command_panel_vote_create_description_desc]
other = "περιγραφή του πίνακα ψηφοφορίας"

[command_panel_vote_create_max_choice]
other = "μέγιστη επιλογή"

[command_panel_vote_create_max_choice_desc]
other = "μέγιστος αριθμός επιλογών"

[command_panel_vote_create_message_add]
other = "Προσθήκη"

[command_panel_vote_create_message_add_choice]
other = "Προσθήκη επιλογής"

[command_panel_vote_create_message_add_vote_choice]
other = "Προσθήκη επιλογών ψήφου"

[command_panel_vote_create_message_create]
other = "Δημιουργία"

[command_panel_vote_create_message_end_at]
other = "Τέλος στις"

[command_panel_vote_create_message_max]
other = "Μέγιστο"

[command_panel_vote_create_message_min]
other = "Ελάχιστο"

[command_panel_vote_create_message_modal_description]
other = "Περιγραφή"

[command_panel_vote_create_message_modal_description_desc]
other = "Περιγραφή της επιλογής ψήφου"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "προαιρετικό"

[command_panel_vote_create_message_modal_title]
other = "Τίτλος"

[command_panel_vote_create_message_modal_title_desc]
other = "Τίτλος της επιλογής ψήφου"

[command_panel_vote_create_message_no_desc]
other = "χωρίς περιγραφή"

[command_panel_vote_create_message_vote_info]
other = "Πληροφορίες ψηφοφορίας"

[command_panel_vote_create_min_choice]
other = "ελάχιστη επιλογή"

[command_panel_vote_create_min_choice_desc]
other = "minimun αριθμός επιλογών"

[command_panel_vote_create_show_count]
other = "εμφάνιση πλήθους"

[command_panel_vote_create_show_count_desc]
other = "δείχνουν τις τιμές της ψήφου"

[command_panel_vote_create_time]
other = "χρονικό όριο"

[command_panel_vote_create_time_desc]
other = "προθεσμία της επιτροπής ψηφοφορίας"

[command_panel_vote_create_time_unit]
other = "μονάδα χρόνου"

[command_panel_vote_create_time_unit_day]
one = "ημέρα"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "μονάδα προθεσμίας"

[command_panel_vote_create_time_unit_hour]
one = "ώρα"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "λεπτό"
other = "minute"

[command_panel_vote_create_title]
other = "τίτλος"

[command_panel_vote_create_title_desc]
other = "τίτλος του πίνακα ψηφοφορίας"

[command_panel_vote_desc]
other = "διαχείριση και δημιουργία πίνακα ψηφοφορίας"

[command_panel_vote_message_finished]
other = "Η ψηφοφορία ολοκληρώθηκε!"

[command_panel_vote_message_result]
other = "Αποτέλεσμα"

[command_panel_vote_message_voted]
other = "Ψηφίστηκε!"

[command_panel_vote_message_winner]
other = "Νικητής"

[command_panel_vote_votes]
one = "{{.Vote}} ψήφος"
other = "{{.Vote}} ψήφοι"

[command_role]
other = "ρόλος"

[command_role_desc]
other = "διαχείριση ρόλου"

[command_role_option_color]
other = "χρώμα"

[command_role_option_color_desc]
other = "δημιουργία ρόλου χρώματος"

[command_role_option_color_option_name]
other = "όνομα"

[command_role_option_color_option_name_desc]
other = "όνομα του ρόλου"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "κωδικός χρώματος rgb"

[command_tracker]
other = "ιχνηλάτης"

[command_tracker_desc]
other = "διαχείριση ή δημιουργία ιχνηλάτη"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "διαχείριση ιχνηλάτη διακομιστή minecraft"

[command_tracker_option_minecraft_option_create]
other = "δημιουργία"

[command_tracker_option_minecraft_option_create_desc]
other = "ιχνηλάτης διακομιστή minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "διεύθυνση"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "διεύθυνση διακομιστή"

[command_tracker_option_minecraft_option_create_option_name]
other = "όνομα"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "όνομα διακομιστή"

[command_tracker_option_minecraft_option_create_option_port]
other = "θύρα"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "θύρα διακομιστή"

[command_tracker_option_minecraft_option_create_option_role]
other = "ρόλος"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "ρόλος να αναφέρουμε"

[command_tracker_option_minecraft_option_get]
other = "πάρε"

[command_tracker_option_minecraft_option_get_desc]
other = "πάρε minecraft trackers"

[command_tracker_option_minecraft_option_remove]
other = "Κατάργηση"

[command_tracker_option_minecraft_option_remove_desc]
other = "αφαίρεσε ιχνηλάτες minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "όνομα"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "όνομα του ιχνηλάτη"

[error]
other = "{{.Error}}"

[error_0]
other = "Παρουσιάστηκε ένα σφάλμα {{.Error}}"

[error_TargetIsBot]
other = "Δεν μπορείτε να επιλέξετε αυτό το bot ως στόχο!"

[error_bot_does_not_have_permissions]
other = "Ανεπαρκή δικαιώματα bot !\rΠρέπει να του δοθεί άδεια διαχειριστή από τον διαχειριστή για να λειτουργήσει!"

[error_cannot_read_content]
other = "Αντιγραφή αναγνωσμένου περιεχομένου μηνύματος."

[error_cannot_use_roles]
other = "Οι ακόλουθοι ρόλοι δεν μπορούν να χρησιμοποιηθούν"

[error_failed_to_connect_api]
other = "αποτυχία σύνδεσης στο σφάλμα διακομιστή api"

[error_failed_to_ping_server]
other = "αποτυχία στο διακομιστή ping"

[error_invalid_port_value]
other = "μη έγκυρη τιμή θύρας"

[error_invalid_roles]
other = "Μη έγκυρος ρόλος"

[error_message]
other = "Παρουσιάστηκε ένα σφάλμα"

[error_unknown_command]
other = "Άγνωστη λειτουργία"

[feed_minecraft_webhook_name]
other = "κοινοποιών διακομιστή"

[latency]
other = "λανθάνουσα κατάσταση"

[message_command_modify]
other = "τροποποίηση"

[message_command_pin]
other = "μήνυμα ακροδέκτη"

[message_command_select]
other = "επιλογή"

[message_command_select_message]
other = "επιλεγμένα"

[message_command_user_info]
other = "πληροφορίες"

[message_command_user_info_color_code]
other = "Κωδικός Χρώματος"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Έγινε μέλος στις"

[message_command_user_info_nick]
other = "Ψευδώνυμο"

[message_command_user_info_none]
other = "κανένα"

[message_command_user_info_roles]
other = "Ρόλοι"

[message_command_user_info_status]
other = "Κατάσταση"

[message_modify_cant_use_this_message_error]
other = "δεν είναι διαθέσιμο για αυτό το μήνυμα"

[message_modify_role_add_message]
other = "Επιλέξτε ένα ρόλο για προσθήκη"

[message_modify_role_create_message]
other = "Χτυπήστε ένα ρόλο για να δημιουργήσετε πίνακα"

[online_status]
other = "Κατάσταση"

[panel_minecraft_add_server]
other = "Προσθήκη διακομιστή"

[panel_minecraft_address]
other = "Διεύθυνση"

[panel_minecraft_display_name]
other = "Εμφανιζόμενο Όνομα"

[panel_minecraft_message_boot]
other = "εκκινήθηκε {{.Name}}"

[panel_minecraft_message_stop]
other = "σταμάτησε {{.Name}}"

[panel_minecraft_my_server]
other = "Ο διακομιστής μου"

[panel_minecraft_port]
other = "Θύρα"

[panel_role_message_added]
other = "προστέθηκε"

[panel_role_message_removed]
other = "αφαιρέθηκε"

[players]
other = "παίκτες"

[port]
other = "θύρα"

[version]
other = "έκδοση"
