[address]
other = "osoite"

[channel]
other = "kanava"

[client_desktop]
other = "Työpöytä"

[client_mobile]
other = "Mobiili"

[client_web]
other = "Verkko"

[command_message]
other = "viesti"

[command_message_description]
other = "hallitse ja lähetä viesti"

[command_message_embed]
other = "upotettu"

[command_message_embed_color]
other = "väri"

[command_message_embed_color_description]
other = "rgb upotetun värin koodi"

[command_message_embed_content]
other = "sisältö"

[command_message_embed_content_description]
other = "viestin sisältö"

[command_message_embed_description]
other = "lähetä upotettu viesti webkoukulla"

[command_message_embed_embed_content]
other = "upotettu sisältö"

[command_message_embed_embed_content_description]
other = "viestin sisältö upotettuna"

[command_message_embed_embed_title]
other = "otsikko"

[command_message_embed_embed_title_description]
other = "viestin otsikko upotettuna"

[command_message_embed_icon_url]
other = "kuvakkeen url"

[command_message_embed_icon_url_description]
other = "käyttäjän avaajan url"

[command_message_embed_username]
other = "käyttäjätunnus"

[command_message_embed_username_description]
other = "viestin lähettäjän nimi"

[command_message_webhook]
other = "webkoukku"

[command_message_webhook_description]
other = "lähetä webhook viesti"

[command_panel]
other = "paneeli"

[command_panel_desc]
other = "hallitse tai luo paneeli"

[command_panel_option_config]
other = "config"

[command_panel_option_config_desc]
other = "konfiguroi proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Aseta mukautetut emojit valikossa"

[command_panel_option_config_option_emoji_message]
other = "Lähetä emojeja tällä kanavalla"

[command_panel_option_desc_role]
other = "hallitse roolipaneelia"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "hallitse minecraft-paneelia"

[command_panel_option_minecraft_message]
other = 'Jos haluat lisätä palvelimen oikealle, paina viestiä pitkään ja paina "Sovellukset" ja "muokata"'

[command_panel_option_minecraft_option_create]
other = "luo"

[command_panel_option_minecraft_option_create_desc]
other = "luo minecraft paneeli"

[command_panel_option_minecraft_option_create_option_address]
other = "osoite"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "palvelimen osoite"

[command_panel_option_minecraft_option_create_option_description]
other = "kuvaus"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "paneelin kuvaus"

[command_panel_option_minecraft_option_create_option_name]
other = "nimi"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "paneelin nimi"

[command_panel_option_minecraft_option_create_option_port]
other = "portti"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "palvelimen portti"

[command_panel_option_minecraft_option_create_option_servername]
other = "palvelimen nimi"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "palvelimen nimi"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "näytä ip tai ei"

[command_panel_option_minecraft_placeholder]
other = "Valitse palvelin"

[command_panel_option_role]
other = "rooli"

[command_panel_option_role_message]
other = 'Voit lisätä roolin oikealle painamalla tai pitämällä viestiä pohjassa ja painamalla "Sovellukset" ja "muokata"'

[command_panel_option_role_option_create]
other = "luo"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "paneelin desc"

[command_panel_option_role_option_create_option_desc_name]
other = "paneelin nimi"

[command_panel_option_role_option_create_option_desc_role]
other = "rooli, joka lisää paneeliin"

[command_panel_option_role_option_create_option_name]
other = "nimi"

[command_panel_option_role_option_create_option_role]
other = "rooli"

[command_panel_option_role_option_desc_create]
other = "luo roolipaneeli"

[command_role]
other = "rooli"

[command_role_desc]
other = "hallitse roolia"

[command_role_option_color]
other = "väri"

[command_role_option_color_desc]
other = "luo värirooli"

[command_role_option_color_option_name]
other = "nimi"

[command_role_option_color_option_name_desc]
other = "roolin nimi"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb värikoodi"

[command_tracker]
other = "seurantapalvelin"

[command_tracker_desc]
other = "hallitse tai luo seurantapalvelin"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "hallitse minecraft palvelimen seuraajaa"

[command_tracker_option_minecraft_option_create]
other = "luo"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft palvelimen seuranta"

[command_tracker_option_minecraft_option_create_option_address]
other = "osoite"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "palvelimen osoite"

[command_tracker_option_minecraft_option_create_option_name]
other = "nimi"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "palvelimen nimi"

[command_tracker_option_minecraft_option_create_option_port]
other = "portti"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "palvelimen portti"

[command_tracker_option_minecraft_option_create_option_role]
other = "rooli"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "maininnan rooli"

[command_tracker_option_minecraft_option_get]
other = "hae"

[command_tracker_option_minecraft_option_get_desc]
other = "hae minecraft trackers"

[command_tracker_option_minecraft_option_remove]
other = "poista"

[command_tracker_option_minecraft_option_remove_desc]
other = "poista minecraftin jäljittäjät"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nimi"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "seurantapalvelimen nimi"

[error]
other = "{{.Error}}"

[error_0]
other = "Tapahtui virhe {{.Error}}"

[error_TargetIsBot]
other = "Botti ei voi valita kohteeksi!"

[error_bot_does_not_have_permissions]
other = "Riittämätön botin käyttöoikeudet!\rPalvelimen ylläpitäjän täytyy antaa järjestelmänvalvojalle lupa toimiakseen!"

[error_cannot_read_content]
other = "Cant lukuviestin sisältö."

[error_cannot_use_roles]
other = "Seuraavia rooleja ei voi käyttää"

[error_failed_to_connect_api]
other = "API-palvelimeen yhdistäminen epäonnistui"

[error_failed_to_ping_server]
other = "palvelimen pingäys epäonnistui"

[error_invalid_port_value]
other = "virheellinen portin arvo"

[error_invalid_roles]
other = "Virheellinen rooli(t)"

[error_message]
other = "Virhe on tapahtunut"

[error_unknown_command]
other = "Tuntematon toiminta"

[feed_minecraft_webhook_name]
other = "palvelimen ilmoittaja"

[latency]
other = "latenssi"

[message_command_modify]
other = "muokkaa"

[message_command_pin]
other = "pin viesti"

[message_command_select]
other = "valitse"

[message_command_select_message]
other = "valittu"

[message_command_user_info]
other = "tiedot"

[message_command_user_info_color_code]
other = "Värin Koodi"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Liittyi klo"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "ei"

[message_command_user_info_roles]
other = "Roolit"

[message_command_user_info_status]
other = "Tila"

[message_modify_cant_use_this_message_error]
other = "ei saatavilla tuossa viestissä"

[message_modify_role_add_message]
other = "Valitse lisättävä rooli"

[message_modify_role_create_message]
other = "Coose rooli luoda paneeli"

[online_status]
other = "Tila"

[panel_minecraft_add_server]
other = "Lisää palvelin"

[panel_minecraft_address]
other = "Osoite"

[panel_minecraft_display_name]
other = "Näytön Nimi"

[panel_minecraft_message_boot]
other = "käynnistetty {{.Name}}"

[panel_minecraft_message_stop]
other = "pysäytettiin {{.Name}}"

[panel_minecraft_my_server]
other = "Oma palvelin"

[panel_minecraft_port]
other = "Portti"

[panel_role_message_added]
other = "lisätty"

[panel_role_message_removed]
other = "poistettu"

[players]
other = "pelaajat"

[port]
other = "portti"

[version]
other = "versio"
