[address]
other = "adresse"

[channel]
other = "canal"

[client_desktop]
other = "Bureau"

[client_mobile]
other = "Téléphone mobile"

[client_web]
other = "Web"

[command_message]
other = "message"

[command_message_description]
other = "gérer et envoyer le message"

[command_message_embed]
other = "intégrer"

[command_message_embed_color]
other = "couleur"

[command_message_embed_color_description]
other = "code rgb de couleur d'embed"

[command_message_embed_content]
other = "contenu"

[command_message_embed_content_description]
other = "contenu du message"

[command_message_embed_description]
other = "envoyer un message intégré avec le webhook"

[command_message_embed_embed_content]
other = "Intégrer le contenu"

[command_message_embed_embed_content_description]
other = "contenu du message intégré"

[command_message_embed_embed_title]
other = "Titre:"

[command_message_embed_embed_title_description]
other = "titre du message intégré"

[command_message_embed_icon_url]
other = "url de l'icône"

[command_message_embed_icon_url_description]
other = "url de l'avatar de l'utilisateur"

[command_message_embed_username]
other = "nom d'utilisateur"

[command_message_embed_username_description]
other = "nom de l'expéditeur du message"

[command_message_webhook]
other = "Webhook"

[command_message_webhook_description]
other = "envoyer un message sur le webhook"

[command_panel]
other = "panneau"

[command_panel_desc]
other = "gérer ou créer un panneau"

[command_panel_option_config]
other = "Configuration"

[command_panel_option_config_desc]
other = "configurer les proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Définir les émojis personnalisés dans le menu de sélection"

[command_panel_option_config_option_emoji_message]
other = "Veuillez envoyer des émojis dans ce canal"

[command_panel_option_desc_role]
other = "gérer le panneau des rôles"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "gérer le panneau minecraft"

[command_panel_option_minecraft_message]
other = 'Pour ajouter un serveur cliquez avec le bouton droit de la souris ou appuyez longuement sur le message et appuyez sur "Apps" puis "modifier"'

[command_panel_option_minecraft_option_create]
other = "créer"

[command_panel_option_minecraft_option_create_desc]
other = "créer un panneau minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_panel_option_minecraft_option_create_option_description]
other = "Libellé"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description du panneau"

[command_panel_option_minecraft_option_create_option_name]
other = "Nom"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nom du panneau"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_panel_option_minecraft_option_create_option_servername]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "afficher l'IP ou pas"

[command_panel_option_minecraft_placeholder]
other = "Sélectionnez le serveur"

[command_panel_option_role]
other = "Rôle"

[command_panel_option_role_message]
other = 'Pour ajouter un rôle cliquez avec le bouton droit de la souris ou maintenez appuyé sur le message et appuyez sur "Apps" puis "modifier"'

[command_panel_option_role_option_create]
other = "créer"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc du panneau"

[command_panel_option_role_option_create_option_desc_name]
other = "nom du panneau"

[command_panel_option_role_option_create_option_desc_role]
other = "rôle qui s'ajoute au panneau"

[command_panel_option_role_option_create_option_name]
other = "Nom"

[command_panel_option_role_option_create_option_role]
other = "Rôle"

[command_panel_option_role_option_desc_create]
other = "créer un panneau de rôle"

[command_panel_vote]
other = "Voter"

[command_panel_vote_create]
other = "créer"

[command_panel_vote_create_desc]
other = "créer un panneau de vote"

[command_panel_vote_create_description]
other = "Libellé"

[command_panel_vote_create_description_desc]
other = "description du panel de vote"

[command_panel_vote_create_max_choice]
other = "choix max"

[command_panel_vote_create_max_choice_desc]
other = "nombre maximum de choix"

[command_panel_vote_create_message_add]
other = "Ajouter"

[command_panel_vote_create_message_add_choice]
other = "Ajouter un choix"

[command_panel_vote_create_message_add_vote_choice]
other = "Ajouter des choix de vote"

[command_panel_vote_create_message_create]
other = "Créer"

[command_panel_vote_create_message_end_at]
other = "Finir à"

[command_panel_vote_create_message_start_at]
other = "Start at"

[command_panel_vote_create_message_max]
other = "Max."

[command_panel_vote_create_message_min]
other = "Min"

[command_panel_vote_create_message_modal_description]
other = "Libellé"

[command_panel_vote_create_message_modal_description_desc]
other = "Description du choix du vote"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "optionnel"

[command_panel_vote_create_message_modal_title]
other = "Titre de la page"

[command_panel_vote_create_message_modal_title_desc]
other = "Titre du choix du vote"

[command_panel_vote_create_message_no_desc]
other = "aucune description"

[command_panel_vote_create_message_vote_info]
other = "Informations sur le vote"

[command_panel_vote_create_min_choice]
other = "choix min"

[command_panel_vote_create_min_choice_desc]
other = "nombre minimum de choix"

[command_panel_vote_create_show_count]
other = "afficher le nombre"

[command_panel_vote_create_show_count_desc]
other = "afficher les valeurs de vote"

[command_panel_vote_create_time]
other = "limite de temps"

[command_panel_vote_create_time_desc]
other = "limite de temps du panel de vote"

[command_panel_vote_create_time_unit]
other = "unité de temps"

[command_panel_vote_create_time_unit_day]
one = "jour"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "unité de temps limite"

[command_panel_vote_create_time_unit_hour]
one = "heure"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "minute"
other = "minute"

[command_panel_vote_create_title]
other = "Titre:"

[command_panel_vote_create_title_desc]
other = "titre du panel de vote"

[command_panel_vote_desc]
other = "gérer et créer le panneau de vote"

[command_panel_vote_message_finished]
other = "Vote terminé !"

[command_panel_vote_message_result]
other = "Résultat"

[command_panel_vote_message_voted]
other = "Voté !"

[command_panel_vote_message_winner]
other = "Gagnant"

[command_panel_vote_votes]
one = "{{.Vote}} votes"
other = "{{.Vote}} votes"

[command_role]
other = "Rôle"

[command_role_desc]
other = "gérer le rôle"

[command_role_option_color]
other = "couleur"

[command_role_option_color_desc]
other = "créer un rôle de couleur"

[command_role_option_color_option_name]
other = "Nom"

[command_role_option_color_option_name_desc]
other = "nom du rôle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "code couleur rgb"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "gérer ou créer un tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gérer le tracker de serveur minecraft"

[command_tracker_option_minecraft_option_create]
other = "créer"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveur minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nom du serveur"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_tracker_option_minecraft_option_create_option_role]
other = "Rôle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rôle à mentionner"

[command_tracker_option_minecraft_option_get]
other = "obtenir"

[command_tracker_option_minecraft_option_get_desc]
other = "obtenir des traqueurs de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Enlever"

[command_tracker_option_minecraft_option_remove_desc]
other = "supprimer les traceurs de minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nom du tracker"

[error]
other = "{{.Error}}"

[error_0]
other = "Une erreur s'est produite {{.Error}}"

[error_TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error_bot_does_not_have_permissions]
other = "Permissions de bot insuffisantes !\rIl doit être donné à l'administrateur par l'administrateur du serveur pour fonctionner !"

[error_cannot_read_content]
other = "Vous ne pouvez pas lire le contenu du message."

[error_cannot_use_roles]
other = "Les rôles suivants ne peuvent pas être utilisés"

[error_failed_to_connect_api]
other = "impossible de se connecter au serveur api"

[error_failed_to_ping_server]
other = "échec du ping du serveur"

[error_invalid_port_value]
other = "valeur de port invalide"

[error_invalid_roles]
other = "Rôle(s) non valide"

[error_message]
other = "Une erreur est survenue"

[error_unknown_command]
other = "Opération inconnue"

[feed_minecraft_webhook_name]
other = "serveur de notification"

[latency]
other = "latence"

[message_command_modify]
other = "modifier"

[message_command_pin]
other = "message épinglé"

[message_command_select]
other = "sélectionner"

[message_command_select_message]
other = "slectionns"

[message_command_user_info]
other = "Infos"

[message_command_user_info_color_code]
other = "Code de couleur"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Inscrit le"

[message_command_user_info_nick]
other = "Pseudo"

[message_command_user_info_none]
other = "aucun"

[message_command_user_info_roles]
other = "Rôles"

[message_command_user_info_status]
other = "Statut"

[message_modify_cant_use_this_message_error]
other = "non disponible pour ce message"

[message_modify_role_add_message]
other = "Choisissez un rôle à ajouter"

[message_modify_role_create_message]
other = "Coose un rôle pour créer un panneau"

[online_status]
other = "Statut"

[panel_minecraft_add_server]
other = "Ajouter un serveur"

[panel_minecraft_address]
other = "Adresses"

[panel_minecraft_display_name]
other = "Nom affiché"

[panel_minecraft_message_boot]
other = "a démarré {{.Name}}"

[panel_minecraft_message_stop]
other = "arrêté {{.Name}}"

[panel_minecraft_my_server]
other = "Mon serveur"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "Ajouté"

[panel_role_message_removed]
other = "enlevé"

[players]
other = "joueurs"

[port]
other = "port"

[version]
other = "version"
