[address]
other = "indirizzo"

[channel]
other = "canale"

[client_desktop]
other = "Desktop"

[client_mobile]
other = "Cellulare"

[client_web]
other = "Web"

[command_message]
other = "messaggio"

[command_message_description]
other = "gestire e inviare messaggi"

[command_message_embed]
other = "incorporato"

[command_message_embed_color]
other = "colore"

[command_message_embed_color_description]
other = "codice rgb di colore incorporato"

[command_message_embed_content]
other = "contenuto"

[command_message_embed_content_description]
other = "contenuto del messaggio"

[command_message_embed_description]
other = "invia un messaggio incorporato con webhook"

[command_message_embed_embed_content]
other = "contenuto di incorporazione"

[command_message_embed_embed_content_description]
other = "contenuto del messaggio incorporato"

[command_message_embed_embed_title]
other = "titolo"

[command_message_embed_embed_title_description]
other = "titolo del messaggio incorporato"

[command_message_embed_icon_url]
other = "url icona"

[command_message_embed_icon_url_description]
other = "url di avater utente"

[command_message_embed_username]
other = "username"

[command_message_embed_username_description]
other = "nome del mittente del messaggio"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "invia messaggio webhook"

[command_panel]
other = "pannello"

[command_panel_desc]
other = "gestire o creare un pannello"

[command_panel_option_config]
other = "configurazione"

[command_panel_option_config_desc]
other = "configura proprities"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Imposta emoji personalizzate nel menu di selezione"

[command_panel_option_config_option_emoji_message]
other = "Invia emoji in questo canale"

[command_panel_option_desc_role]
other = "gestire il pannello ruoli"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "gestire pannello minecraft"

[command_panel_option_minecraft_message]
other = 'Per aggiungere un server fare clic con il tasto destro o premere a lungo sul messaggio e premere "Apps" quindi "modifica"'

[command_panel_option_minecraft_option_create]
other = "crea"

[command_panel_option_minecraft_option_create_desc]
other = "crea pannello minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "indirizzo"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "indirizzo del server"

[command_panel_option_minecraft_option_create_option_description]
other = "descrizione"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrizione del pannello"

[command_panel_option_minecraft_option_create_option_name]
other = "nome"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nome del pannello"

[command_panel_option_minecraft_option_create_option_port]
other = "porta"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "porta del server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nome del server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostra ip o no"

[command_panel_option_minecraft_placeholder]
other = "Seleziona server"

[command_panel_option_role]
other = "ruolo"

[command_panel_option_role_message]
other = 'Per aggiungere un ruolo, clicca con il tasto destro o tieni premuto il messaggio e premi "Apps" e poi "modifica"'

[command_panel_option_role_option_create]
other = "crea"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del pannello"

[command_panel_option_role_option_create_option_desc_name]
other = "nome del pannello"

[command_panel_option_role_option_create_option_desc_role]
other = "ruolo che si aggiunge al pannello"

[command_panel_option_role_option_create_option_name]
other = "nome"

[command_panel_option_role_option_create_option_role]
other = "ruolo"

[command_panel_option_role_option_desc_create]
other = "crea pannello ruolo"

[command_panel_vote]
other = "vota"

[command_panel_vote_create]
other = "crea"

[command_panel_vote_create_desc]
other = "crea il comitato di voto"

[command_panel_vote_create_description]
other = "descrizione"

[command_panel_vote_create_description_desc]
other = "descrizione della commissione di voto"

[command_panel_vote_create_max_choice]
other = "scelta massima"

[command_panel_vote_create_max_choice_desc]
other = "numero massimo di scelte"

[command_panel_vote_create_message_add]
other = "Add"

[command_panel_vote_create_message_add_choice]
other = "Add choice"

[command_panel_vote_create_message_add_vote_choice]
other = "Add vote choices"

[command_panel_vote_create_message_create]
other = "Create"

[command_panel_vote_create_message_end_at]
other = "End at"

[command_panel_vote_create_message_max]
other = "Max"

[command_panel_vote_create_message_min]
other = "Min"

[command_panel_vote_create_message_modal_description]
other = "Description"

[command_panel_vote_create_message_modal_description_desc]
other = "Description of vote choice"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "optional"

[command_panel_vote_create_message_modal_title]
other = "Title"

[command_panel_vote_create_message_modal_title_desc]
other = "Title of vote choice"

[command_panel_vote_create_message_no_desc]
other = "no description"

[command_panel_vote_create_message_vote_info]
other = "Vote info"

[command_panel_vote_create_min_choice]
other = "scelta min"

[command_panel_vote_create_min_choice_desc]
other = "numero minimo di scelte"

[command_panel_vote_create_show_count]
other = "mostra conteggio"

[command_panel_vote_create_show_count_desc]
other = "mostra i valori della votazione"

[command_panel_vote_create_time]
other = "limite di tempo"

[command_panel_vote_create_time_desc]
other = "limite di tempo per la commissione di voto"

[command_panel_vote_create_time_unit]
other = "unità di tempo"

[command_panel_vote_create_time_unit_day]
one = "day"
other = "days"

[command_panel_vote_create_time_unit_desc]
other = "unità di tempo limite"

[command_panel_vote_create_time_unit_hour]
one = "hour"
other = "hours"

[command_panel_vote_create_time_unit_minute]
one = "minute"
other = "minutes"

[command_panel_vote_create_title]
other = "titolo"

[command_panel_vote_create_title_desc]
other = "titolo della commissione di voto"

[command_panel_vote_desc]
other = "gestire e creare un pannello di voto"

[command_panel_vote_message_finished]
other = "Vote finished!"

[command_panel_vote_message_result]
other = "Result"

[command_panel_vote_message_voted]
other = "Voted!"

[command_panel_vote_message_winner]
other = "Winner"

[command_panel_vote_votes]
one = "{{.Vote}} vote"
other = "{{.Vote}} votes"

[command_role]
other = "ruolo"

[command_role_desc]
other = "gestisci ruolo"

[command_role_option_color]
other = "colore"

[command_role_option_color_desc]
other = "crea ruolo colore"

[command_role_option_color_option_name]
other = "nome"

[command_role_option_color_option_name_desc]
other = "nome del ruolo"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "codice colore rgb"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "gestisci o crea tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gestisci server tracker di minecraft"

[command_tracker_option_minecraft_option_create]
other = "crea"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "indirizzo"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "indirizzo del server"

[command_tracker_option_minecraft_option_create_option_name]
other = "nome"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nome del server"

[command_tracker_option_minecraft_option_create_option_port]
other = "porta"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "porta del server"

[command_tracker_option_minecraft_option_create_option_role]
other = "ruolo"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "ruolo da menzionare"

[command_tracker_option_minecraft_option_get]
other = "ottieni"

[command_tracker_option_minecraft_option_get_desc]
other = "ottieni tracker minecraft"

[command_tracker_option_minecraft_option_remove]
other = "rimuovi"

[command_tracker_option_minecraft_option_remove_desc]
other = "rimuovi minecraft trackers"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nome"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nome del tracker"

[error]
other = "{{.Error}}"

[error_0]
other = "Si è verificato un errore {{.Error}}"

[error_TargetIsBot]
other = "Non è possibile selezionare questo bot come obiettivo!"

[error_bot_does_not_have_permissions]
other = "Permessi bot insufficienti!\rDeve essere dato all'amministratore il permesso del server per funzionare!"

[error_cannot_read_content]
other = "Cant read message content"

[error_cannot_use_roles]
other = "I seguenti ruoli non possono essere utilizzati"

[error_failed_to_connect_api]
other = "errore di connessione del server api non riuscito"

[error_failed_to_ping_server]
other = "ping del server non riuscito"

[error_invalid_port_value]
other = "valore porta non valido"

[error_invalid_roles]
other = "Ruoli non validi"

[error_message]
other = "Si è verificato un errore"

[error_unknown_command]
other = "Operazione sconosciuta"

[feed_minecraft_webhook_name]
other = "notificatore server"

[latency]
other = "latenza"

[message_command_modify]
other = "modifica"

[message_command_pin]
other = "messaggio pin"

[message_command_select]
other = "seleziona"

[message_command_select_message]
other = "selezionato"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Codice Colore"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Iscritto il"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "nessuno"

[message_command_user_info_roles]
other = "Ruoli"

[message_command_user_info_status]
other = "Stato"

[message_modify_cant_use_this_message_error]
other = "non disponibile per quel messaggio"

[message_modify_role_add_message]
other = "Scegli un ruolo da aggiungere"

[message_modify_role_create_message]
other = "Scegli un ruolo per creare un pannello"

[online_status]
other = "Stato"

[panel_minecraft_add_server]
other = "Aggiungi un server"

[panel_minecraft_address]
other = "Indirizzo"

[panel_minecraft_display_name]
other = "Nome Visualizzato"

[panel_minecraft_message_boot]
other = "avviato {{.Name}}"

[panel_minecraft_message_stop]
other = "fermato {{.Name}}"

[panel_minecraft_my_server]
other = "Il mio server"

[panel_minecraft_port]
other = "Porta"

[panel_role_message_added]
other = "aggiunto"

[panel_role_message_removed]
other = "rimosso"

[players]
other = "giocatori"

[port]
other = "porta"

[version]
other = "versione"
