[address]
other = "アドレス"

[channel]
other = "チャンネル"

[client_desktop]
other = "デスクトップ"

[client_mobile]
other = "モバイル"

[client_web]
other = "ウェブ"

[command_message]
other = "メッセージ"

[command_message_description]
other = "メッセージを管理、送信する"

[command_message_embed]
other = "埋め込み"

[command_message_embed_color]
other = "カラー"

[command_message_embed_color_description]
other = "埋め込みカラーのRGBコード"

[command_message_embed_content]
other = "コンテンツ"

[command_message_embed_content_description]
other = "メッセージの内容"

[command_message_embed_description]
other = "ウェブフックで埋め込みメッセージを送信する"

[command_message_embed_embed_content]
other = "埋め込むコンテンツ"

[command_message_embed_embed_content_description]
other = "メッセージ埋め込みの内容"

[command_message_embed_embed_title]
other = "タイトル"

[command_message_embed_embed_title_description]
other = "メッセージ埋め込みのタイトル"

[command_message_embed_icon_url]
other = "アイコン URL"

[command_message_embed_icon_url_description]
other = "ユーザーアバターのURL"

[command_message_embed_username]
other = "ユーザー名"

[command_message_embed_username_description]
other = "メッセージ送信者の名前"

[command_message_webhook]
other = "ウェブフック"

[command_message_webhook_description]
other = "ウェブフックメッセージの送信"

[command_panel]
other = "パネル"

[command_panel_desc]
other = "パネルの管理または作成"

[command_panel_option_config]
other = "設定"

[command_panel_option_config_desc]
other = "プロパティを設定"

[command_panel_option_config_option_emoji]
other = "絵文字"

[command_panel_option_config_option_emoji_desc]
other = "セレクトメニューにカスタム絵文字を設定"

[command_panel_option_config_option_emoji_message]
other = "このチャンネルに絵文字を送信してください"

[command_panel_option_desc_role]
other = "役割パネルの管理"

[command_panel_option_minecraft]
other = "マインクラフト"

[command_panel_option_minecraft_desc]
other = "マインクラフトパネルを管理"

[command_panel_option_minecraft_message]
other = "サーバーを追加するには、メッセージを右クリックまたは長押しして「アプリ」と「変更」を押します"

[command_panel_option_minecraft_option_create]
other = "作成"

[command_panel_option_minecraft_option_create_desc]
other = "マインクラフトパネルを作成"

[command_panel_option_minecraft_option_create_option_address]
other = "アドレス"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_panel_option_minecraft_option_create_option_description]
other = "説明"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "パネルの説明"

[command_panel_option_minecraft_option_create_option_name]
other = "名前"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "パネル名"

[command_panel_option_minecraft_option_create_option_port]
other = "ポート"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_panel_option_minecraft_option_create_option_servername]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_showip]
other = "ipを表示"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "IPを表示するかどうか"

[command_panel_option_minecraft_placeholder]
other = "サーバーを選択"

[command_panel_option_role]
other = "ロール"

[command_panel_option_role_message]
other = "ロールを追加するには、メッセージを右クリックまたは長押しして「アプリ」と「変更」を押します"

[command_panel_option_role_option_create]
other = "作成"

[command_panel_option_role_option_create_option_desc]
other = "説明"

[command_panel_option_role_option_create_option_desc_desc]
other = "パネルの説明"

[command_panel_option_role_option_create_option_desc_name]
other = "パネル名"

[command_panel_option_role_option_create_option_desc_role]
other = "パネルに追加するロール"

[command_panel_option_role_option_create_option_name]
other = "名前"

[command_panel_option_role_option_create_option_role]
other = "ロール"

[command_panel_option_role_option_desc_create]
other = "役割パネルを作成"

[command_panel_vote]
other = "投票"

[command_panel_vote_create]
other = "作成"

[command_panel_vote_create_desc]
other = "投票パネルを作成"

[command_panel_vote_create_description]
other = "説明"

[command_panel_vote_create_description_desc]
other = "投票パネルの説明"

[command_panel_vote_create_max_choice]
other = "最大選択数"

[command_panel_vote_create_max_choice_desc]
other = "選択の最大数"

[command_panel_vote_create_message_add]
other = "追加"

[command_panel_vote_create_message_add_choice]
other = "選択肢を追加"

[command_panel_vote_create_message_add_vote_choice]
other = "投票の選択肢を追加"

[command_panel_vote_create_message_create]
other = "作成"

[command_panel_vote_create_message_end_at]
other = "終了"

[command_panel_vote_create_message_start_at]
other = "開始"

[command_panel_vote_create_message_max]
other = "最大"

[command_panel_vote_create_message_min]
other = "最小"

[command_panel_vote_create_message_modal_description]
other = "説明"

[command_panel_vote_create_message_modal_description_desc]
other = "投票の選択肢の説明"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "任意"

[command_panel_vote_create_message_modal_title]
other = "タイトル"

[command_panel_vote_create_message_modal_title_desc]
other = "選択肢のタイトル"

[command_panel_vote_create_message_no_desc]
other = "説明なし"

[command_panel_vote_create_message_vote_info]
other = "投票情報"

[command_panel_vote_create_min_choice]
other = "最小選択数"

[command_panel_vote_create_min_choice_desc]
other = "選択の最小数"

[command_panel_vote_create_show_count]
other = "数を表示する"

[command_panel_vote_create_show_count_desc]
other = "投票数を表示"

[command_panel_vote_create_time]
other = "時間制限"

[command_panel_vote_create_time_desc]
other = "投票パネルの制限時間"

[command_panel_vote_create_time_unit]
other = "時間単位"

[command_panel_vote_create_time_unit_day]
one = "日"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "時間制限の単位"

[command_panel_vote_create_time_unit_hour]
one = "時間"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "分"
other = "minute"

[command_panel_vote_create_title]
other = "タイトル"

[command_panel_vote_create_title_desc]
other = "投票パネルのタイトル"

[command_panel_vote_desc]
other = "投票パネルを管理、作成する"

[command_panel_vote_message_finished]
other = "投票終了！"

[command_panel_vote_message_result]
other = "結果"

[command_panel_vote_message_voted]
other = "投票しました!"

[command_panel_vote_message_winner]
other = "勝者"

[command_panel_vote_votes]
one = "{{.Vote}} 票"
other = "{{.Vote}} 票"

[command_role]
other = "ロール"

[command_role_desc]
other = "ロール管理"

[command_role_option_color]
other = "カラー"

[command_role_option_color_desc]
other = "カラーロールを作成"

[command_role_option_color_option_name]
other = "名前"

[command_role_option_color_option_name_desc]
other = "ロールの名前"

[command_role_option_color_option_rgb]
other = "RGB"

[command_role_option_color_option_rgb_desc]
other = "RGBカラーコード"

[command_tracker]
other = "トラッカー"

[command_tracker_desc]
other = "トラッカーを管理または作成する"

[command_tracker_option_minecraft]
other = "マインクラフト"

[command_tracker_option_minecraft_desc]
other = "マインクラフトサーバートラッカーを管理する"

[command_tracker_option_minecraft_option_create]
other = "作成"

[command_tracker_option_minecraft_option_create_desc]
other = "マインクラフトサーバートラッカー"

[command_tracker_option_minecraft_option_create_option_address]
other = "アドレス"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_tracker_option_minecraft_option_create_option_name]
other = "名前"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "サーバー名"

[command_tracker_option_minecraft_option_create_option_port]
other = "ポート"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_tracker_option_minecraft_option_create_option_role]
other = "ロール"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "メンションするロール"

[command_tracker_option_minecraft_option_get]
other = "取得"

[command_tracker_option_minecraft_option_get_desc]
other = "マインクラフトのトラッカーを取得します"

[command_tracker_option_minecraft_option_remove]
other = "削除"

[command_tracker_option_minecraft_option_remove_desc]
other = "マインクラフトのトラッカーを削除します"

[command_tracker_option_minecraft_option_remove_option_name]
other = "名前"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "トラッカーの名前"

[error]
other = "{{.Error}}"

[error_0]
other = "エラーが発生しました： {{.Error}}"

[error_TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error_bot_does_not_have_permissions]
other = "Botの権限が不足しています！\r管理者権限を与える必要があります！"

[error_cannot_read_content]
other = "メッセージの内容を読み取ることができません"

[error_cannot_use_roles]
other = "次のロールは使用できません"

[error_failed_to_connect_api]
other = "APIサーバーの接続に失敗しました"

[error_failed_to_ping_server]
other = "サーバーへの接続に失敗しました"

[error_invalid_port_value]
other = "不正なポート値"

[error_invalid_roles]
other = "無効な役割です"

[error_message]
other = "エラーが発生しました"

[error_unknown_command]
other = "不明な動作"

[feed_minecraft_webhook_name]
other = "サーバ通知"

[latency]
other = "レイテンシ"

[message_command_modify]
other = "変更"

[message_command_pin]
other = "ピン留め"

[message_command_select]
other = "選択"

[message_command_select_message]
other = "選択済み"

[message_command_user_info]
other = "情報"

[message_command_user_info_color_code]
other = "カラーコード"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "参加日時"

[message_command_user_info_nick]
other = "ニックネーム"

[message_command_user_info_none]
other = "無し"

[message_command_user_info_roles]
other = "ロール"

[message_command_user_info_status]
other = "ステータス"

[message_modify_cant_use_this_message_error]
other = "そのメッセージでは利用できません"

[message_modify_role_add_message]
other = "追加するロールを選択してください"

[message_modify_role_create_message]
other = "作成するパネルに追加するロールを選んで下さい"

[online_status]
other = "ステータス"

[panel_minecraft_add_server]
other = "サーバーを追加"

[panel_minecraft_address]
other = "住所"

[panel_minecraft_display_name]
other = "表示名"

[panel_minecraft_message_boot]
other = "{{.Name}} が起動しました"

[panel_minecraft_message_stop]
other = "{{.Name}} が停止しました"

[panel_minecraft_my_server]
other = "私のサーバー"

[panel_minecraft_port]
other = "ポート"

[panel_role_message_added]
other = "追加"

[panel_role_message_removed]
other = "剥奪"

[players]
other = "プレイヤー"

[port]
other = "ポート"

[version]
other = "バージョン"
