[address]
other = "adresse"

[channel]
other = "kanal"

[client_desktop]
other = "Skrivebord"

[client_mobile]
other = "Mobil"

[client_web]
other = "Nett"

[command_message]
other = "melding"

[command_message_description]
other = "behandle og sende melding"

[command_message_embed]
other = "Fiks"

[command_message_embed_color]
other = "farge"

[command_message_embed_color_description]
other = "rgb-kode for innebygd farge"

[command_message_embed_content]
other = "innhold"

[command_message_embed_content_description]
other = "innhold i melding"

[command_message_embed_description]
other = "send en tilkoblet melding med webhook"

[command_message_embed_embed_content]
other = "Innebygd innhold"

[command_message_embed_embed_content_description]
other = "innhold i en seng"

[command_message_embed_embed_title]
other = "tittel"

[command_message_embed_embed_title_description]
other = "tittel på en melding"

[command_message_embed_icon_url]
other = "URL for ikon"

[command_message_embed_icon_url_description]
other = "url til brukeravsender"

[command_message_embed_username]
other = "brukernavn"

[command_message_embed_username_description]
other = "Navn på meldingavsender"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "send webhook melding"

[command_panel]
other = "panel"

[command_panel_desc]
other = "administrer eller opprett panel"

[command_panel_option_config]
other = "Konfigurasjon"

[command_panel_option_config_desc]
other = "Konfigurer proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Sett egendefinerte emoji i velg meny"

[command_panel_option_config_option_emoji_message]
other = "Vennligst send emoji i denne kanalen"

[command_panel_option_desc_role]
other = "administrere rollepanelet"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "administrere minecraft panel"

[command_panel_option_minecraft_message]
other = 'For å legge til en server høyre, klikk eller trykk lenge på meldingen og trykk "Apps" og deretter "endre"'

[command_panel_option_minecraft_option_create]
other = "Opprett"

[command_panel_option_minecraft_option_create_desc]
other = "opprett minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adressen til serveren"

[command_panel_option_minecraft_option_create_option_description]
other = "beskrivelse"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "beskrivelse av panel"

[command_panel_option_minecraft_option_create_option_name]
other = "navn"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "navn på panelet"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port av serveren"

[command_panel_option_minecraft_option_create_option_servername]
other = "servernavn"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "navnet på serveren"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "vis ip eller ikke"

[command_panel_option_minecraft_placeholder]
other = "Velg server"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_message]
other = 'For å legge til en rolle høyre, klikk eller hold i meldingen og trykk "Apps" og deretter "endre"'

[command_panel_option_role_option_create]
other = "Opprett"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "Beskrivelse av panel"

[command_panel_option_role_option_create_option_desc_name]
other = "navn på panelet"

[command_panel_option_role_option_create_option_desc_role]
other = "rolle som legger til i panelet"

[command_panel_option_role_option_create_option_name]
other = "navn"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "opprett rollepanel"

[command_panel_vote]
other = "Stem"

[command_panel_vote_create]
other = "Opprett"

[command_panel_vote_create_desc]
other = "opprett stemme panel"

[command_panel_vote_create_description]
other = "beskrivelse"

[command_panel_vote_create_description_desc]
other = "beskrivelse av valgpanelet"

[command_panel_vote_create_max_choice]
other = "maksimalt valg"

[command_panel_vote_create_max_choice_desc]
other = "største antall valg"

[command_panel_vote_create_message_add]
other = "Add"

[command_panel_vote_create_message_add_choice]
other = "Add choice"

[command_panel_vote_create_message_add_vote_choice]
other = "Add vote choices"

[command_panel_vote_create_message_create]
other = "Create"

[command_panel_vote_create_message_end_at]
other = "End at"

[command_panel_vote_create_message_max]
other = "Max"

[command_panel_vote_create_message_min]
other = "Min"

[command_panel_vote_create_message_modal_description]
other = "Description"

[command_panel_vote_create_message_modal_description_desc]
other = "Description of vote choice"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "optional"

[command_panel_vote_create_message_modal_title]
other = "Title"

[command_panel_vote_create_message_modal_title_desc]
other = "Title of vote choice"

[command_panel_vote_create_message_no_desc]
other = "no description"

[command_panel_vote_create_message_vote_info]
other = "Vote info"

[command_panel_vote_create_min_choice]
other = "min. valg"

[command_panel_vote_create_min_choice_desc]
other = "minimerer antall valg"

[command_panel_vote_create_show_count]
other = "vis antall"

[command_panel_vote_create_show_count_desc]
other = "vis verdiene av stemme"

[command_panel_vote_create_time]
other = "tidsgrense"

[command_panel_vote_create_time_desc]
other = "tidsgrensen til kontrollpanelet"

[command_panel_vote_create_time_unit]
other = "tidsenhet"

[command_panel_vote_create_time_unit_day]
one = "day"
other = "days"

[command_panel_vote_create_time_unit_desc]
other = "enhet av tidsgrense"

[command_panel_vote_create_time_unit_hour]
one = "hour"
other = "hours"

[command_panel_vote_create_time_unit_minute]
one = "minute"
other = "minutes"

[command_panel_vote_create_title]
other = "tittel"

[command_panel_vote_create_title_desc]
other = "tittelen på valgpanelet"

[command_panel_vote_desc]
other = "administrere og opprette avstemningspanelet"

[command_panel_vote_message_finished]
other = "Vote finished!"

[command_panel_vote_message_result]
other = "Result"

[command_panel_vote_message_voted]
other = "Voted!"

[command_panel_vote_message_winner]
other = "Winner"

[command_panel_vote_votes]
one = "{{.Vote}} vote"
other = "{{.Vote}} votes"

[command_role]
other = "rolle"

[command_role_desc]
other = "administrere rolle"

[command_role_option_color]
other = "farge"

[command_role_option_color_desc]
other = "opprett fargerolle"

[command_role_option_color_option_name]
other = "navn"

[command_role_option_color_option_name_desc]
other = "navn på rolle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb fargekode"

[command_tracker]
other = "sporing"

[command_tracker_desc]
other = "administrere eller opprette tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "administrer tracker for minecraft"

[command_tracker_option_minecraft_option_create]
other = "Opprett"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adressen til serveren"

[command_tracker_option_minecraft_option_create_option_name]
other = "navn"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "navnet på serveren"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port av serveren"

[command_tracker_option_minecraft_option_create_option_role]
other = "rolle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rolle for å nevne"

[command_tracker_option_minecraft_option_get]
other = "hent"

[command_tracker_option_minecraft_option_get_desc]
other = "få minecraft sporere"

[command_tracker_option_minecraft_option_remove]
other = "fjern"

[command_tracker_option_minecraft_option_remove_desc]
other = "fjern minecraft sporere"

[command_tracker_option_minecraft_option_remove_option_name]
other = "navn"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "tracker navn"

[error]
other = "{{.Error}}"

[error_0]
other = "En feil har oppstått {{.Error}}"

[error_TargetIsBot]
other = "Kan ikke velge denne botten som mål!"

[error_bot_does_not_have_permissions]
other = "Utilstrekkelige bot tillatelser!\rDet må gis administratorrettigheter av serveradministratoren til å virke!"

[error_cannot_read_content]
other = "Kant lese meldingsinnholdet."

[error_cannot_use_roles]
other = "Følgende roller kan ikke brukes"

[error_failed_to_connect_api]
other = "kunne ikke koble til server feil"

[error_failed_to_ping_server]
other = "kunne ikke ping av server"

[error_invalid_port_value]
other = "ugyldig port-verdi"

[error_invalid_roles]
other = "Ugyldige rolle(r)"

[error_message]
other = "En feil har oppstått"

[error_unknown_command]
other = "Ukjent operasjon"

[feed_minecraft_webhook_name]
other = "varsling av tjener"

[latency]
other = "latens"

[message_command_modify]
other = "endre"

[message_command_pin]
other = "PIN melding"

[message_command_select]
other = "velg"

[message_command_select_message]
other = "valgt"

[message_command_user_info]
other = "informasjon"

[message_command_user_info_color_code]
other = "Farge Kode"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Ble med"

[message_command_user_info_nick]
other = "Kallenavn"

[message_command_user_info_none]
other = "ingen"

[message_command_user_info_roles]
other = "Roller"

[message_command_user_info_status]
other = "Status:"

[message_modify_cant_use_this_message_error]
other = "ikke tilgjengelig for den meldingen"

[message_modify_role_add_message]
other = "Velg en rolle å legge til"

[message_modify_role_create_message]
other = "Kos en rolle for å opprette panel"

[online_status]
other = "Status:"

[panel_minecraft_add_server]
other = "Legg til server"

[panel_minecraft_address]
other = "Adresse"

[panel_minecraft_display_name]
other = "Vis navn"

[panel_minecraft_message_boot]
other = "startet {{.Name}}"

[panel_minecraft_message_stop]
other = "stoppet {{.Name}}"

[panel_minecraft_my_server]
other = "Min server"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "lagt til"

[panel_role_message_removed]
other = "fjernet"

[players]
other = "spillere"

[port]
other = "port"

[version]
other = "versjon"
