[address]
other = "adres"

[channel]
other = "kanał"

[client_desktop]
other = "Pulpit"

[client_mobile]
other = "Komórka"

[client_web]
other = "Web"

[command_message]
other = "wiadomość"

[command_message_description]
other = "zarządzaj i wysyłaj wiadomość"

[command_message_embed]
other = "osadzony"

[command_message_embed_color]
other = "kolor"

[command_message_embed_color_description]
other = "kod rgb koloru osadzonego"

[command_message_embed_content]
other = "zawartość"

[command_message_embed_content_description]
other = "treść wiadomości"

[command_message_embed_description]
other = "wyślij wiadomość osadzoną przez webhook"

[command_message_embed_embed_content]
other = "zawartość osadzenia"

[command_message_embed_embed_content_description]
other = "zawartość osadzonych wiadomości"

[command_message_embed_embed_title]
other = "tytuł"

[command_message_embed_embed_title_description]
other = "tytuł osadzonej wiadomości"

[command_message_embed_icon_url]
other = "adres url ikony"

[command_message_embed_icon_url_description]
other = "URL awatera użytkownika"

[command_message_embed_username]
other = "nazwa użytkownika"

[command_message_embed_username_description]
other = "nazwa nadawcy wiadomości"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "wyślij wiadomość webhook"

[command_panel]
other = "panele"

[command_panel_desc]
other = "zarządzaj lub utwórz panel"

[command_panel_option_config]
other = "konfiguracja"

[command_panel_option_config_desc]
other = "skonfiguruj proprity"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Ustaw niestandardowe emoji w menu wyboru"

[command_panel_option_config_option_emoji_message]
other = "Proszę wysłać emoji na tym kanale"

[command_panel_option_desc_role]
other = "zarządzanie panelem ról"

[command_panel_option_minecraft]
other = "rzemiosło"

[command_panel_option_minecraft_desc]
other = "zarządzanie panelem minecraft"

[command_panel_option_minecraft_message]
other = 'Aby dodać serwer kliknij prawym przyciskiem myszy lub przytrzymaj wiadomość i naciśnij "Aplikacje", a następnie "mody"'

[command_panel_option_minecraft_option_create]
other = "utwórz"

[command_panel_option_minecraft_option_create_desc]
other = "utwórz panel minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adres"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adres serwera"

[command_panel_option_minecraft_option_create_option_description]
other = "opis"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "opis panelu"

[command_panel_option_minecraft_option_create_option_name]
other = "Nazwa"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nazwa panelu"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port serwera"

[command_panel_option_minecraft_option_create_option_servername]
other = "nazwa serwera"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nazwa serwera"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "pokaż IP lub nie"

[command_panel_option_minecraft_placeholder]
other = "Wybierz serwer"

[command_panel_option_role]
other = "Rola"

[command_panel_option_role_message]
other = 'Aby dodać rolę kliknij prawym przyciskiem myszy lub naciśnij i przytrzymaj wiadomość i naciśnij "Aplikacje", a następnie "mody"'

[command_panel_option_role_option_create]
other = "utwórz"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc panelu"

[command_panel_option_role_option_create_option_desc_name]
other = "nazwa panelu"

[command_panel_option_role_option_create_option_desc_role]
other = "rola, która dodaje do panelu"

[command_panel_option_role_option_create_option_name]
other = "Nazwa"

[command_panel_option_role_option_create_option_role]
other = "Rola"

[command_panel_option_role_option_desc_create]
other = "utwórz panel ról"

[command_panel_vote]
other = "zagłosuj"

[command_panel_vote_create]
other = "utwórz"

[command_panel_vote_create_desc]
other = "utwórz panel głosów"

[command_panel_vote_create_description]
other = "opis"

[command_panel_vote_create_description_desc]
other = "opis panelu do głosowania"

[command_panel_vote_create_max_choice]
other = "maksymalny wybór"

[command_panel_vote_create_max_choice_desc]
other = "maksymalna liczba wyborów"

[command_panel_vote_create_message_add]
other = "Add"

[command_panel_vote_create_message_add_choice]
other = "Add choice"

[command_panel_vote_create_message_add_vote_choice]
other = "Add vote choices"

[command_panel_vote_create_message_create]
other = "Create"

[command_panel_vote_create_message_end_at]
other = "End at"

[command_panel_vote_create_message_max]
other = "Max"

[command_panel_vote_create_message_min]
other = "Min"

[command_panel_vote_create_message_modal_description]
other = "Description"

[command_panel_vote_create_message_modal_description_desc]
other = "Description of vote choice"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "optional"

[command_panel_vote_create_message_modal_title]
other = "Title"

[command_panel_vote_create_message_modal_title_desc]
other = "Title of vote choice"

[command_panel_vote_create_message_no_desc]
other = "no description"

[command_panel_vote_create_message_vote_info]
other = "Vote info"

[command_panel_vote_create_min_choice]
other = "Minimalny wybór"

[command_panel_vote_create_min_choice_desc]
other = "minimun liczba wyborów"

[command_panel_vote_create_show_count]
other = "pokaż liczbę"

[command_panel_vote_create_show_count_desc]
other = "pokaż wartości głosowania"

[command_panel_vote_create_time]
other = "termin"

[command_panel_vote_create_time_desc]
other = "termin głosowania komisji"

[command_panel_vote_create_time_unit]
other = "jednostka czasu"

[command_panel_vote_create_time_unit_day]
one = "day"
other = "days"

[command_panel_vote_create_time_unit_desc]
other = "jednostka limitu czasowego"

[command_panel_vote_create_time_unit_hour]
one = "hour"
other = "hours"

[command_panel_vote_create_time_unit_minute]
one = "minute"
other = "minutes"

[command_panel_vote_create_title]
other = "tytuł"

[command_panel_vote_create_title_desc]
other = "tytuł komisji ds. głosowania"

[command_panel_vote_desc]
other = "zarządzaj i twórz panel głosów"

[command_panel_vote_message_finished]
other = "Vote finished!"

[command_panel_vote_message_result]
other = "Result"

[command_panel_vote_message_voted]
other = "Voted!"

[command_panel_vote_message_winner]
other = "Winner"

[command_panel_vote_votes]
one = "{{.Vote}} vote"
other = "{{.Vote}} votes"

[command_role]
other = "Rola"

[command_role_desc]
other = "zarządzanie rolą"

[command_role_option_color]
other = "kolor"

[command_role_option_color_desc]
other = "utwórz rolę kolorów"

[command_role_option_color_option_name]
other = "Nazwa"

[command_role_option_color_option_name_desc]
other = "nazwa roli"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "kod koloru rgb"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "zarządzaj lub utwórz tracker"

[command_tracker_option_minecraft]
other = "rzemiosło"

[command_tracker_option_minecraft_desc]
other = "zarządzanie śledzeniem serwera minecraft"

[command_tracker_option_minecraft_option_create]
other = "utwórz"

[command_tracker_option_minecraft_option_create_desc]
other = "tropiciel serwera minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adres"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adres serwera"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nazwa"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nazwa serwera"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port serwera"

[command_tracker_option_minecraft_option_create_option_role]
other = "Rola"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rola do wzmianki"

[command_tracker_option_minecraft_option_get]
other = "pobierz"

[command_tracker_option_minecraft_option_get_desc]
other = "pobierz tropiciele minecraft"

[command_tracker_option_minecraft_option_remove]
other = "usuń"

[command_tracker_option_minecraft_option_remove_desc]
other = "usuń tropiciele minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nazwa"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nazwa trackera"

[error]
other = "{{.Error}}"

[error_0]
other = "Wystąpił błąd {{.Error}}"

[error_TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error_bot_does_not_have_permissions]
other = "Niewystarczające uprawnienia bota!\rAdministrator musi otrzymać uprawnienia administratora serwera do pracy!"

[error_cannot_read_content]
other = "Przeczytaj zawartość wiadomości."

[error_cannot_use_roles]
other = "Nie można użyć następujących ról"

[error_failed_to_connect_api]
other = "błąd połączenia z serwerem api"

[error_failed_to_ping_server]
other = "nie udało się wyczyścić serwera"

[error_invalid_port_value]
other = "nieprawidłowa wartość portu"

[error_invalid_roles]
other = "Nieprawidłowe role"

[error_message]
other = "Wystąpił błąd"

[error_unknown_command]
other = "Operacja nieznana"

[feed_minecraft_webhook_name]
other = "powiadomienie serwera"

[latency]
other = "opóźnienie"

[message_command_modify]
other = "modyfikacja"

[message_command_pin]
other = "komunikat pin"

[message_command_select]
other = "wybierz"

[message_command_select_message]
other = "zaznaczone"

[message_command_user_info]
other = "informacje"

[message_command_user_info_color_code]
other = "Kod koloru"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Dołączył do"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "brak"

[message_command_user_info_roles]
other = "Role"

[message_command_user_info_status]
other = "Status"

[message_modify_cant_use_this_message_error]
other = "niedostępne dla tej wiadomości"

[message_modify_role_add_message]
other = "Wybierz rolę do dodania"

[message_modify_role_create_message]
other = "Przypomnij rolę do utworzenia panelu"

[online_status]
other = "Status"

[panel_minecraft_add_server]
other = "Dodaj serwer"

[panel_minecraft_address]
other = "Adres"

[panel_minecraft_display_name]
other = "Wyświetlana nazwa"

[panel_minecraft_message_boot]
other = "uruchomiono {{.Name}}"

[panel_minecraft_message_stop]
other = "zatrzymano {{.Name}}"

[panel_minecraft_my_server]
other = "Mój serwer"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "dodany"

[panel_role_message_removed]
other = "usunięto"

[players]
other = "gracze"

[port]
other = "port"

[version]
other = "wersja"
