[address]
other = "Endereço"

[channel]
other = "Canal"

[client_desktop]
other = "Computadores"

[client_mobile]
other = "Celular"

[client_web]
other = "Web"

[command_message]
other = "Mensagem"

[command_message_description]
other = "gerenciar e enviar mensagem"

[command_message_embed]
other = "Incorporar"

[command_message_embed_color]
other = "cor"

[command_message_embed_color_description]
other = "Código RGB de cor incorporada"

[command_message_embed_content]
other = "conteúdo"

[command_message_embed_content_description]
other = "conteúdo da mensagem"

[command_message_embed_description]
other = "enviar mensagem de incorporação com webhook"

[command_message_embed_embed_content]
other = "incorporação de conteúdo"

[command_message_embed_embed_content_description]
other = "conteúdo da mensagem incorporada"

[command_message_embed_embed_title]
other = "Título"

[command_message_embed_embed_title_description]
other = "título da mensagem incorporada"

[command_message_embed_icon_url]
other = "URL do ícone"

[command_message_embed_icon_url_description]
other = "URL do avatar do usuário"

[command_message_embed_username]
other = "usuário"

[command_message_embed_username_description]
other = "nome do remetente da mensagem"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "enviar mensagem de webhook"

[command_panel]
other = "painel"

[command_panel_desc]
other = "gerenciar ou criar painel"

[command_panel_option_config]
other = "configuração"

[command_panel_option_config_desc]
other = "configurar perfis"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Definir emojis personalizados no menu de seleção"

[command_panel_option_config_option_emoji_message]
other = "Por favor, envie emojis neste canal"

[command_panel_option_desc_role]
other = "gerenciar painel de funções"

[command_panel_option_minecraft]
other = "Minecraft"

[command_panel_option_minecraft_desc]
other = "gerenciar painel do minecraft"

[command_panel_option_minecraft_message]
other = 'Para adicionar um servidor clique com o botão direito ou mantenha pressionado na mensagem e pressione "Apps" e "Modificar"'

[command_panel_option_minecraft_option_create]
other = "criar"

[command_panel_option_minecraft_option_create_desc]
other = "criar painel de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Endereço"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_panel_option_minecraft_option_create_option_description]
other = "Descrição"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrição do painel"

[command_panel_option_minecraft_option_create_option_name]
other = "Nome"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nome do painel"

[command_panel_option_minecraft_option_create_option_port]
other = "Porta"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_panel_option_minecraft_option_create_option_servername]
other = "nomedoServidor"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nome do servidor"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostrar o IP ou não"

[command_panel_option_minecraft_placeholder]
other = "Selecionar servidor"

[command_panel_option_role]
other = "Função"

[command_panel_option_role_message]
other = 'Para adicionar um papel clique com o botão direito ou pressione e segure na mensagem e pressione "Apps" e "Modificar"'

[command_panel_option_role_option_create]
other = "criar"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "DESC do painel"

[command_panel_option_role_option_create_option_desc_name]
other = "nome do painel"

[command_panel_option_role_option_create_option_desc_role]
other = "função que adicionar ao painel"

[command_panel_option_role_option_create_option_name]
other = "Nome"

[command_panel_option_role_option_create_option_role]
other = "Função"

[command_panel_option_role_option_desc_create]
other = "criar painel de função"

[command_role]
other = "Função"

[command_role_desc]
other = "gerenciar função"

[command_role_option_color]
other = "cor"

[command_role_option_color_desc]
other = "criar função de cor"

[command_role_option_color_option_name]
other = "Nome"

[command_role_option_color_option_name_desc]
other = "nome da função"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "Código de cor RGB"

[command_tracker]
other = "rastreador"

[command_tracker_desc]
other = "gerenciar ou criar rastreador"

[command_tracker_option_minecraft]
other = "Minecraft"

[command_tracker_option_minecraft_desc]
other = "gerenciar rastreador de servidores do minecraft"

[command_tracker_option_minecraft_option_create]
other = "criar"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft rastreador de servidores"

[command_tracker_option_minecraft_option_create_option_address]
other = "Endereço"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nome do servidor"

[command_tracker_option_minecraft_option_create_option_port]
other = "Porta"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_tracker_option_minecraft_option_create_option_role]
other = "Função"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "função para mencionar"

[command_tracker_option_minecraft_option_get]
other = "obtenha"

[command_tracker_option_minecraft_option_get_desc]
other = "obter rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Remover"

[command_tracker_option_minecraft_option_remove_desc]
other = "remover rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nome do rastreador"

[error]
other = "{{.Error}}"

[error_0]
other = "Ocorreu um erro {{.Error}}"

[error_TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error_bot_does_not_have_permissions]
other = "Permissões de bot insuficientes!\rEle deve ser dado permissão de administrador pelo administrador do servidor para funcionar!"

[error_cannot_read_content]
other = "Não é possível ler o conteúdo da mensagem."

[error_cannot_use_roles]
other = "Não é possível usar as seguintes funções"

[error_failed_to_connect_api]
other = "falha ao conectar erro do servidor api"

[error_failed_to_ping_server]
other = "falha ao fazer ping no servidor"

[error_invalid_port_value]
other = "valor de porta inválida"

[error_invalid_roles]
other = "Papéis inválidos"

[error_message]
other = "Ocorreu um erro"

[error_unknown_command]
other = "Operação desconhecida"

[feed_minecraft_webhook_name]
other = "notificador do servidor"

[latency]
other = "latência"

[message_command_modify]
other = "Modificar"

[message_command_pin]
other = "fixar mensagem"

[message_command_select]
other = "selecionar"

[message_command_select_message]
other = "Selecionado"

[message_command_user_info]
other = "informações"

[message_command_user_info_color_code]
other = "Código de cor"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Entrou em"

[message_command_user_info_nick]
other = "Apelido"

[message_command_user_info_none]
other = "nenhuma"

[message_command_user_info_roles]
other = "Papéis"

[message_command_user_info_status]
other = "SItuação"

[message_modify_cant_use_this_message_error]
other = "não disponível para essa mensagem"

[message_modify_role_add_message]
other = "Escolha um cargo para adicionar"

[message_modify_role_create_message]
other = "Codir uma função para criar um painel"

[online_status]
other = "SItuação"

[panel_minecraft_add_server]
other = "Adicionar um servidor"

[panel_minecraft_address]
other = "Endereço"

[panel_minecraft_display_name]
other = "Nome para exibição"

[panel_minecraft_message_boot]
other = "inicializado em {{.Name}}"

[panel_minecraft_message_stop]
other = "parou {{.Name}}"

[panel_minecraft_my_server]
other = "Meu servidor"

[panel_minecraft_port]
other = "Porta"

[panel_role_message_added]
other = "adicionado"

[panel_role_message_removed]
other = "removido"

[players]
other = "Jogadores"

[port]
other = "Porta"

[version]
other = "Versão"

[command_panel_vote]
other = "vote"

[command_panel_vote_desc]
other = "manage and create vote panel"

[command_panel_vote_create]
other = "create"

[command_panel_vote_create_desc]
other = "create vote panel"

[command_panel_vote_create_title]
other = "title"

[command_panel_vote_create_title_desc]
other = "title of vote panel"

[command_panel_vote_create_description]
other = "description"

[command_panel_vote_create_description_desc]
other = "description of vote panel"

[command_panel_vote_create_time]
other = "time limit"

[command_panel_vote_create_time_desc]
other = "time limit of vote panel"

[command_panel_vote_create_time_unit]
other = "time unit"

[command_panel_vote_create_time_unit_desc]
other = "unit of time limit"

[command_panel_vote_create_time_unit_day]
other = "day"

[command_panel_vote_create_time_unit_hour]
other = "hour"

[command_panel_vote_create_time_unit_minute]
other = "minute"

[command_panel_vote_create_min_choice]
other = "min choice"

[command_panel_vote_create_min_choice_desc]
other = "minimun number of choices"

[command_panel_vote_create_max_choice]
other = "max choice"

[command_panel_vote_create_max_choice_desc]
other = "maximum number of choices"

[command_panel_vote_create_show_count]
other = "show count"

[command_panel_vote_create_show_count_desc]
other = "show the values of vote"
