[address]
other = "adresă"

[channel]
other = "canal"

[client_desktop]
other = "Birou"

[client_mobile]
other = "Mobil"

[client_web]
other = "Web"

[command_message]
other = "mesaj"

[command_message_description]
other = "gestionează și trimite mesajul"

[command_message_embed]
other = "încorporat"

[command_message_embed_color]
other = "culoare"

[command_message_embed_color_description]
other = "cod rgb de culoare încorporată"

[command_message_embed_content]
other = "Conținut"

[command_message_embed_content_description]
other = "conținutul mesajului"

[command_message_embed_description]
other = "trimite mesaj încorporat cu webhook"

[command_message_embed_embed_content]
other = "încorporare conținut"

[command_message_embed_embed_content_description]
other = "conținutul mesajului încorporat"

[command_message_embed_embed_title]
other = "titlu"

[command_message_embed_embed_title_description]
other = "titlul mesajului încorporat"

[command_message_embed_icon_url]
other = "URL pictogramă"

[command_message_embed_icon_url_description]
other = "url of user avater"

[command_message_embed_username]
other = "utilizator"

[command_message_embed_username_description]
other = "numele expeditorului mesajului"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "trimite mesaj webhook"

[command_panel]
other = "panou"

[command_panel_desc]
other = "gestionare sau creare panou"

[command_panel_option_config]
other = "configurare"

[command_panel_option_config_desc]
other = "configurare proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Setați emoji particularizate în meniul selectare"

[command_panel_option_config_option_emoji_message]
other = "Te rugăm să trimiți emoji în acest canal"

[command_panel_option_desc_role]
other = "gestionează panoul de rol"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "Gestionează panoul de minecraft"

[command_panel_option_minecraft_message]
other = 'Pentru a adăuga un server la dreapta faceţi clic sau apăsaţi lung pe mesaj şi apăsaţi "Aplicaţii", apoi "Modificaţi"'

[command_panel_option_minecraft_option_create]
other = "crează"

[command_panel_option_minecraft_option_create_desc]
other = "creează panou de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adresă"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresa serverului"

[command_panel_option_minecraft_option_create_option_description]
other = "descriere"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrierea panoului"

[command_panel_option_minecraft_option_create_option_name]
other = "nume"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "numele panoului"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "portul de server"

[command_panel_option_minecraft_option_create_option_servername]
other = "nume server"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "numele serverului"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "arată ip sau nu"

[command_panel_option_minecraft_placeholder]
other = "Selectează server"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_message]
other = 'Pentru a adăuga un rol la dreapta, apăsați și țineți apăsat mesajul și apăsați "Aplicații", apoi "Modificați"'

[command_panel_option_role_option_create]
other = "crează"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "descoperirea panoului"

[command_panel_option_role_option_create_option_desc_name]
other = "numele panoului"

[command_panel_option_role_option_create_option_desc_role]
other = "rol care adaugă la panou"

[command_panel_option_role_option_create_option_name]
other = "nume"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "creează panou de rol"

[command_panel_vote]
other = "vot"

[command_panel_vote_create]
other = "crează"

[command_panel_vote_create_desc]
other = "creează panou de vot"

[command_panel_vote_create_description]
other = "descriere"

[command_panel_vote_create_description_desc]
other = "descrierea comisiei de vot"

[command_panel_vote_create_max_choice]
other = "alegere maximă"

[command_panel_vote_create_max_choice_desc]
other = "numărul maxim de opțiuni"

[command_panel_vote_create_message_add]
other = "Adăugare"

[command_panel_vote_create_message_add_choice]
other = "Adăugați o alegere"

[command_panel_vote_create_message_add_vote_choice]
other = "Adaugă alegeri de vot"

[command_panel_vote_create_message_create]
other = "Crează"

[command_panel_vote_create_message_end_at]
other = "Sfârșit la"

[command_panel_vote_create_message_max]
other = "Maxim"

[command_panel_vote_create_message_min]
other = "Minim"

[command_panel_vote_create_message_modal_description]
other = "Descriere"

[command_panel_vote_create_message_modal_description_desc]
other = "Descrierea alegerii votului"

[command_panel_vote_create_message_modal_description_desc_optional]
other = "opţional"

[command_panel_vote_create_message_modal_title]
other = "Titlu"

[command_panel_vote_create_message_modal_title_desc]
other = "Titlul alegerii privind votul"

[command_panel_vote_create_message_no_desc]
other = "fără descriere"

[command_panel_vote_create_message_vote_info]
other = "Informații votare"

[command_panel_vote_create_min_choice]
other = "alegere min"

[command_panel_vote_create_min_choice_desc]
other = "numărul minim de opțiuni"

[command_panel_vote_create_show_count]
other = "arată număr"

[command_panel_vote_create_show_count_desc]
other = "afișează valorile votului"

[command_panel_vote_create_time]
other = "termen"

[command_panel_vote_create_time_desc]
other = "limita de timp a panoului de vot"

[command_panel_vote_create_time_unit]
other = "unitate de timp"

[command_panel_vote_create_time_unit_day]
one = "zi"
other = "day"

[command_panel_vote_create_time_unit_desc]
other = "unitate de timp limită"

[command_panel_vote_create_time_unit_hour]
one = "oră"
other = "hour"

[command_panel_vote_create_time_unit_minute]
one = "minut"
other = "minute"

[command_panel_vote_create_title]
other = "titlu"

[command_panel_vote_create_title_desc]
other = "Titlul panoului de vot"

[command_panel_vote_desc]
other = "gestionează și creează panoul de vot"

[command_panel_vote_message_finished]
other = "Votare finalizată!"

[command_panel_vote_message_result]
other = "Rezultat"

[command_panel_vote_message_voted]
other = "Votat!"

[command_panel_vote_message_winner]
other = "Câștigător"

[command_panel_vote_votes]
one = "{{.Vote}} vot"
other = "{{.Vote}} voturi"

[command_role]
other = "rol"

[command_role_desc]
other = "gestionează rolul"

[command_role_option_color]
other = "culoare"

[command_role_option_color_desc]
other = "creează rol de culoare"

[command_role_option_color_option_name]
other = "nume"

[command_role_option_color_option_name_desc]
other = "numele rolului"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "cod de culoare rgb"

[command_tracker]
other = "urmăritor"

[command_tracker_desc]
other = "gestionează sau creează tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gestionează trackerul serverului de minecraft"

[command_tracker_option_minecraft_option_create]
other = "crează"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker server minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresă"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresa serverului"

[command_tracker_option_minecraft_option_create_option_name]
other = "nume"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "numele serverului"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "portul de server"

[command_tracker_option_minecraft_option_create_option_role]
other = "rol"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rol de menționat"

[command_tracker_option_minecraft_option_get]
other = "obține"

[command_tracker_option_minecraft_option_get_desc]
other = "obține trackere minecraft"

[command_tracker_option_minecraft_option_remove]
other = "elimină"

[command_tracker_option_minecraft_option_remove_desc]
other = "elimină trackere minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nume"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "numele trackerului"

[error]
other = "{{.Error}}"

[error_0]
other = "S-a produs o eroare {{.Error}}"

[error_TargetIsBot]
other = "Nu se poate selecta acest bot ca țintă!"

[error_bot_does_not_have_permissions]
other = "Permisiuni de bot insuficiente!\rTrebuie să primească permisiunea administratorului serverului pentru a lucra!"

[error_cannot_read_content]
other = "Conținutul mesajelor citite de cant."

[error_cannot_use_roles]
other = "Următoarele roluri nu pot fi utilizate"

[error_failed_to_connect_api]
other = "Eroare la conectarea serverului APi"

[error_failed_to_ping_server]
other = "Eșec la ping-ul serverului"

[error_invalid_port_value]
other = "valoare port nevalidă"

[error_invalid_roles]
other = "Roluri nevalide"

[error_message]
other = "A apărut o eroare"

[error_unknown_command]
other = "Operațiune Neconsolidată"

[feed_minecraft_webhook_name]
other = "notificatorul serverului"

[latency]
other = "latență"

[message_command_modify]
other = "modifică"

[message_command_pin]
other = "pin mesaj"

[message_command_select]
other = "selectează"

[message_command_select_message]
other = "selectat"

[message_command_user_info]
other = "informaţii"

[message_command_user_info_color_code]
other = "Cod culoare"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "S-a alăturat la"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "niciunul"

[message_command_user_info_roles]
other = "Roluri"

[message_command_user_info_status]
other = "Status"

[message_modify_cant_use_this_message_error]
other = "nu este disponibil pentru acel mesaj"

[message_modify_role_add_message]
other = "Alege un rol de adăugat"

[message_modify_role_create_message]
other = "Alege un rol pentru a crea panoul"

[online_status]
other = "Status"

[panel_minecraft_add_server]
other = "Adaugă un server"

[panel_minecraft_address]
other = "Adresa"

[panel_minecraft_display_name]
other = "Nume afișat"

[panel_minecraft_message_boot]
other = "{{.Name}} pornit"

[panel_minecraft_message_stop]
other = "s-a oprit {{.Name}}"

[panel_minecraft_my_server]
other = "Serverul meu"

[panel_minecraft_port]
other = "Portul"

[panel_role_message_added]
other = "adăugat"

[panel_role_message_removed]
other = "eliminat"

[players]
other = "jucători"

[port]
other = "port"

[version]
other = "versiune"
